/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/array_arg.h>
CPS_START_NAMESPACE
	 bool FloatArray::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool FloatArray::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool FloatArray::Vml(VML *vmls,char *instance){
		 if(!vml_FloatArray(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_FloatArray (VML *vmls, char *name,FloatArray *objp)
{
	register int32_t *buf;

	 vml_class_begin(vmls,"FloatArray",name);
	 if (!vml_array (vmls, "Floats", (char **)&objp->Floats.Floats_val, (u_int *) &objp->Floats.Floats_len, ~0,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 vml_class_end(vmls,"FloatArray",name);
	return TRUE;
}
CPS_END_NAMESPACE
