/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/bfm_arg.h>
CPS_START_NAMESPACE
	 bool BfmArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool BfmArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool BfmArg::Vml(VML *vmls,char *instance){
		 if(!vml_BfmArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_BfmArg (VML *vmls, char *name,BfmArg *objp)
{
	 vml_class_begin(vmls,"BfmArg",name);
	 if (!vml_BfmSolverType (vmls, "solver", &objp->solver))
		 return FALSE;
	 if (!vml_int (vmls, "solveMobiusDminus", &objp->solveMobiusDminus))
		 return FALSE;
	 if (!vml_int (vmls, "Ls", &objp->Ls))
		 return FALSE;
	 if (!vml_Float (vmls, "M5", &objp->M5))
		 return FALSE;
	 if (!vml_Float (vmls, "mass", &objp->mass))
		 return FALSE;
	 if (!vml_Float (vmls, "twistedmass", &objp->twistedmass))
		 return FALSE;
	 if (!vml_Float (vmls, "Csw", &objp->Csw))
		 return FALSE;
	 if (!vml_Float (vmls, "zolo_delta", &objp->zolo_delta))
		 return FALSE;
	 if (!vml_Float (vmls, "zolo_lo", &objp->zolo_lo))
		 return FALSE;
	 if (!vml_Float (vmls, "zolo_hi", &objp->zolo_hi))
		 return FALSE;
	 if (!vml_int (vmls, "list_engine", &objp->list_engine))
		 return FALSE;
	 if (!vml_int (vmls, "list_length", &objp->list_length))
		 return FALSE;
	 if (!vml_int (vmls, "powerloop", &objp->powerloop))
		 return FALSE;
	 if (!vml_int (vmls, "time_report_iter", &objp->time_report_iter))
		 return FALSE;
	 if (!vml_int (vmls, "max_iter", &objp->max_iter))
		 return FALSE;
	 if (!vml_Float (vmls, "residual", &objp->residual))
		 return FALSE;
	 if (!vml_int (vmls, "precon_5d", &objp->precon_5d))
		 return FALSE;
	 if (!vml_int (vmls, "reproduce", &objp->reproduce))
		 return FALSE;
	 if (!vml_int (vmls, "reproduce_checksum", &objp->reproduce_checksum))
		 return FALSE;
	 if (!vml_int (vmls, "reproduce_master_check", &objp->reproduce_master_check))
		 return FALSE;
	 if (!vml_int (vmls, "threads", &objp->threads))
		 return FALSE;
	 if (!vml_int (vmls, "verbose", &objp->verbose))
		 return FALSE;
	 if (!vml_int (vmls, "onepluskappanorm", &objp->onepluskappanorm))
		 return FALSE;
	 if (!vml_Float (vmls, "mobius_scale", &objp->mobius_scale))
		 return FALSE;
	 vml_class_end(vmls,"BfmArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
