/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/cg_arg.h>
CPS_START_NAMESPACE
	 bool CgArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool CgArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool CgArg::Vml(VML *vmls,char *instance){
		 if(!vml_CgArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_CgArg (VML *vmls, char *name,CgArg *objp)
{
	 vml_class_begin(vmls,"CgArg",name);
	 if (!vml_Float (vmls, "mass", &objp->mass))
		 return FALSE;
	 if (!vml_int (vmls, "max_num_iter", &objp->max_num_iter))
		 return FALSE;
	 if (!vml_Float (vmls, "stop_rsd", &objp->stop_rsd))
		 return FALSE;
	 if (!vml_Float (vmls, "true_rsd", &objp->true_rsd))
		 return FALSE;
	 if (!vml_RitzMatType (vmls, "RitzMatOper", &objp->RitzMatOper))
		 return FALSE;
	 if (!vml_InverterType (vmls, "Inverter", &objp->Inverter))
		 return FALSE;
	 if (!vml_int (vmls, "bicgstab_n", &objp->bicgstab_n))
		 return FALSE;
	 vml_class_end(vmls,"CgArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
