/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/dens_arg.h>
CPS_START_NAMESPACE

bool_t
vml_DENS_LIM (VML *vmls, char *name,DENS_LIM *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,DENS_LIM_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map DENS_LIM_map[] = {
	{"DENS_LIM","MAX_DENS_MASSES",MAX_DENS_MASSES},
	{"DENS_LIM","MAX_DENS_OBS",MAX_DENS_OBS},
	{NULL,NULL,0}
};
	 bool DensArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool DensArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool DensArg::Vml(VML *vmls,char *instance){
		 if(!vml_DensArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_DensArg (VML *vmls, char *name,DensArg *objp)
{
	 vml_class_begin(vmls,"DensArg",name);
	int i;
	 if (!vml_int (vmls, "n_src", &objp->n_src))
		 return FALSE;
	 if (!vml_int (vmls, "max_deri", &objp->max_deri))
		 return FALSE;
	 if (!vml_int (vmls, "max_save", &objp->max_save))
		 return FALSE;
	 if (!vml_int (vmls, "n_obs", &objp->n_obs))
		 return FALSE;
	 if (!vml_vector (vmls, "obs", (char *)objp->obs, MAX_DENS_OBS,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_PatternType (vmls, "pattern_kind", &objp->pattern_kind))
		 return FALSE;
	 if (!vml_int (vmls, "n_masses", &objp->n_masses))
		 return FALSE;
	 if (!vml_Float (vmls, "mass_start", &objp->mass_start))
		 return FALSE;
	 if (!vml_Float (vmls, "mass_step", &objp->mass_step))
		 return FALSE;
	 if (!vml_vector (vmls, "mass", (char *)objp->mass, MAX_DENS_MASSES,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_int (vmls, "max_num_iter", &objp->max_num_iter))
		 return FALSE;
	 if (!vml_Float (vmls, "stop_rsd", &objp->stop_rsd))
		 return FALSE;
	 if (!vml_int (vmls, "src_u_s", &objp->src_u_s))
		 return FALSE;
	 if (!vml_int (vmls, "src_l_s", &objp->src_l_s))
		 return FALSE;
	 if (!vml_int (vmls, "snk_u_s", &objp->snk_u_s))
		 return FALSE;
	 if (!vml_int (vmls, "snk_l_s", &objp->snk_l_s))
		 return FALSE;
	 if (!vml_int (vmls, "snk_loop", &objp->snk_loop))
		 return FALSE;
	 vml_class_end(vmls,"DensArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
