/*
 * Please do not edit this file.
 * It was generated by CPC make system.
 */

#include "alg/do_arg.h"
CPS_START_NAMESPACE
	 DoArg::DoArg (char *file) {
	   Decode(file,"instance");
	 };
	 void DoArg::Encode(char *filename,char *instance){
		 VML vmls;
		 vmls.Create(filename,VML_ENCODE);
		 Vml(&vmls,instance);
		 vmls.Destroy();
	 }

	 void DoArg::Decode(char *filename,char *instance){
		 VML vmls;
		 vmls.Create(filename,VML_DECODE);
		 Vml(&vmls,instance);
		 vmls.Destroy();
	 }
	 void DoArg::Vml(VML *vmls,char *instance){
		 vml_DoArg(vmls,instance,this);
	 }


bool_t
vml_DoArg (VML *vmls, char *name,DoArg *objp)
{
	register int32_t *buf;

	 vml_class_begin(vmls,"DoArg",name);
	int i;
	 if (!vml_int (vmls, "x_sites", &objp->x_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "y_sites", &objp->y_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "z_sites", &objp->z_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "t_sites", &objp->t_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "s_sites", &objp->s_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "x_node_sites", &objp->x_node_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "y_node_sites", &objp->y_node_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "z_node_sites", &objp->z_node_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "t_node_sites", &objp->t_node_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "s_node_sites", &objp->s_node_sites))
		 return VML_FALSE;
	 if (!vml_int (vmls, "x_nodes", &objp->x_nodes))
		 return VML_FALSE;
	 if (!vml_int (vmls, "y_nodes", &objp->y_nodes))
		 return VML_FALSE;
	 if (!vml_int (vmls, "z_nodes", &objp->z_nodes))
		 return VML_FALSE;
	 if (!vml_int (vmls, "t_nodes", &objp->t_nodes))
		 return VML_FALSE;
	 if (!vml_int (vmls, "s_nodes", &objp->s_nodes))
		 return VML_FALSE;
	 if (!vml_int (vmls, "updates", &objp->updates))
		 return VML_FALSE;
	 if (!vml_int (vmls, "measurements", &objp->measurements))
		 return VML_FALSE;
	 if (!vml_int (vmls, "measurefreq", &objp->measurefreq))
		 return VML_FALSE;
	 if (!vml_BndCndType (vmls, "x_bc", &objp->x_bc))
		 return VML_FALSE;
	 if (!vml_BndCndType (vmls, "y_bc", &objp->y_bc))
		 return VML_FALSE;
	 if (!vml_BndCndType (vmls, "z_bc", &objp->z_bc))
		 return VML_FALSE;
	 if (!vml_BndCndType (vmls, "t_bc", &objp->t_bc))
		 return VML_FALSE;
	 if (!vml_StartConfType (vmls, "start_conf_kind", &objp->start_conf_kind))
		 return VML_FALSE;
	 if (!vml_u_long (vmls, "start_conf_load_addr", &objp->start_conf_load_addr))
		 return VML_FALSE;
	 if (!vml_StartSeedType (vmls, "start_seed_kind", &objp->start_seed_kind))
		 return VML_FALSE;
	 if (!vml_vector (vmls, "start_conf_filename", (char *)objp->start_conf_filename, 50,
		sizeof (char), (vmlproc_t) vml_char))
		 return VML_FALSE;
	 if (!vml_int (vmls, "start_conf_alloc_flag", &objp->start_conf_alloc_flag))
		 return VML_FALSE;
	 if (!vml_int (vmls, "start_seed_value", &objp->start_seed_value))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "beta", &objp->beta))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "c_1", &objp->c_1))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "u0", &objp->u0))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "dwf_height", &objp->dwf_height))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "dwf_a5_inv", &objp->dwf_a5_inv))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "power_plaq_cutoff", &objp->power_plaq_cutoff))
		 return VML_FALSE;
	 if (!vml_int (vmls, "power_plaq_exponent", &objp->power_plaq_exponent))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "power_rect_cutoff", &objp->power_rect_cutoff))
		 return VML_FALSE;
	 if (!vml_int (vmls, "power_rect_exponent", &objp->power_rect_exponent))
		 return VML_FALSE;
	 if (!vml_int (vmls, "verbose_level", &objp->verbose_level))
		 return VML_FALSE;
	 if (!vml_int (vmls, "exec_task_list", &objp->exec_task_list))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "xi_bare", &objp->xi_bare))
		 return VML_FALSE;
	 if (!vml_int (vmls, "xi_dir", &objp->xi_dir))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "xi_v", &objp->xi_v))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "xi_v_xi", &objp->xi_v_xi))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "clover_coeff", &objp->clover_coeff))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "clover_coeff_xi", &objp->clover_coeff_xi))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "xi_gfix", &objp->xi_gfix))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "asqtad_KS", &objp->asqtad_KS))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "asqtad_naik", &objp->asqtad_naik))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "asqtad_3staple", &objp->asqtad_3staple))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "asqtad_5staple", &objp->asqtad_5staple))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "asqtad_7staple", &objp->asqtad_7staple))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "asqtad_lepage", &objp->asqtad_lepage))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "p4_KS", &objp->p4_KS))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "p4_knight", &objp->p4_knight))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "p4_3staple", &objp->p4_3staple))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "p4_5staple", &objp->p4_5staple))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "p4_7staple", &objp->p4_7staple))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "p4_lepage", &objp->p4_lepage))
		 return VML_FALSE;
	 vml_class_end(vmls,"DoArg",name);
	return VML_TRUE;
}
CPS_END_NAMESPACE
