/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/do_arg.h>
CPS_START_NAMESPACE
	 bool BGLAxisMap::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool BGLAxisMap::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool BGLAxisMap::Vml(VML *vmls,char *instance){
		 if(!vml_BGLAxisMap(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_BGLAxisMap (VML *vmls, char *name,BGLAxisMap *objp)
{
	 vml_class_begin(vmls,"BGLAxisMap",name);
	 if (!vml_int (vmls, "bgl_machine_dir_x", &objp->bgl_machine_dir_x))
		 return FALSE;
	 if (!vml_int (vmls, "bgl_machine_dir_y", &objp->bgl_machine_dir_y))
		 return FALSE;
	 if (!vml_int (vmls, "bgl_machine_dir_z", &objp->bgl_machine_dir_z))
		 return FALSE;
	 if (!vml_int (vmls, "bgl_machine_dir_t", &objp->bgl_machine_dir_t))
		 return FALSE;
	 vml_class_end(vmls,"BGLAxisMap",name);
	return TRUE;
}
	 bool DoArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool DoArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool DoArg::Vml(VML *vmls,char *instance){
		 if(!vml_DoArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_DoArg (VML *vmls, char *name,DoArg *objp)
{
	 vml_class_begin(vmls,"DoArg",name);
	 if (!vml_int (vmls, "x_sites", &objp->x_sites))
		 return FALSE;
	 if (!vml_int (vmls, "y_sites", &objp->y_sites))
		 return FALSE;
	 if (!vml_int (vmls, "z_sites", &objp->z_sites))
		 return FALSE;
	 if (!vml_int (vmls, "t_sites", &objp->t_sites))
		 return FALSE;
	 if (!vml_int (vmls, "s_sites", &objp->s_sites))
		 return FALSE;
	 if (!vml_int (vmls, "x_node_sites", &objp->x_node_sites))
		 return FALSE;
	 if (!vml_int (vmls, "y_node_sites", &objp->y_node_sites))
		 return FALSE;
	 if (!vml_int (vmls, "z_node_sites", &objp->z_node_sites))
		 return FALSE;
	 if (!vml_int (vmls, "t_node_sites", &objp->t_node_sites))
		 return FALSE;
	 if (!vml_int (vmls, "s_node_sites", &objp->s_node_sites))
		 return FALSE;
	 if (!vml_int (vmls, "x_nodes", &objp->x_nodes))
		 return FALSE;
	 if (!vml_int (vmls, "y_nodes", &objp->y_nodes))
		 return FALSE;
	 if (!vml_int (vmls, "z_nodes", &objp->z_nodes))
		 return FALSE;
	 if (!vml_int (vmls, "t_nodes", &objp->t_nodes))
		 return FALSE;
	 if (!vml_int (vmls, "s_nodes", &objp->s_nodes))
		 return FALSE;
	 if (!vml_int (vmls, "updates", &objp->updates))
		 return FALSE;
	 if (!vml_int (vmls, "measurements", &objp->measurements))
		 return FALSE;
	 if (!vml_int (vmls, "measurefreq", &objp->measurefreq))
		 return FALSE;
	 if (!vml_int (vmls, "cg_reprod_freq", &objp->cg_reprod_freq))
		 return FALSE;
	 if (!vml_BndCndType (vmls, "x_bc", &objp->x_bc))
		 return FALSE;
	 if (!vml_BndCndType (vmls, "y_bc", &objp->y_bc))
		 return FALSE;
	 if (!vml_BndCndType (vmls, "z_bc", &objp->z_bc))
		 return FALSE;
	 if (!vml_BndCndType (vmls, "t_bc", &objp->t_bc))
		 return FALSE;
	 if (!vml_StartConfType (vmls, "start_conf_kind", &objp->start_conf_kind))
		 return FALSE;
	 if (!vml_u_long (vmls, "start_conf_load_addr", &objp->start_conf_load_addr))
		 return FALSE;
	 if (!vml_StartSeedType (vmls, "start_seed_kind", &objp->start_seed_kind))
		 return FALSE;
	 if (!vml_string (vmls, "start_seed_filename", &objp->start_seed_filename, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "start_conf_filename", &objp->start_conf_filename, ~0))
		 return FALSE;
	 if (!vml_int (vmls, "start_conf_alloc_flag", &objp->start_conf_alloc_flag))
		 return FALSE;
	 if (!vml_int (vmls, "wfm_alloc_flag", &objp->wfm_alloc_flag))
		 return FALSE;
	 if (!vml_int (vmls, "wfm_send_alloc_flag", &objp->wfm_send_alloc_flag))
		 return FALSE;
	 if (!vml_int (vmls, "start_seed_value", &objp->start_seed_value))
		 return FALSE;
	 if (!vml_Float (vmls, "beta", &objp->beta))
		 return FALSE;
	 if (!vml_Float (vmls, "c_1", &objp->c_1))
		 return FALSE;
	 if (!vml_Float (vmls, "u0", &objp->u0))
		 return FALSE;
	 if (!vml_Float (vmls, "dwf_height", &objp->dwf_height))
		 return FALSE;
	 if (!vml_Float (vmls, "dwf_a5_inv", &objp->dwf_a5_inv))
		 return FALSE;
	 if (!vml_Float (vmls, "power_plaq_cutoff", &objp->power_plaq_cutoff))
		 return FALSE;
	 if (!vml_int (vmls, "power_plaq_exponent", &objp->power_plaq_exponent))
		 return FALSE;
	 if (!vml_Float (vmls, "power_rect_cutoff", &objp->power_rect_cutoff))
		 return FALSE;
	 if (!vml_int (vmls, "power_rect_exponent", &objp->power_rect_exponent))
		 return FALSE;
	 if (!vml_int (vmls, "verbose_level", &objp->verbose_level))
		 return FALSE;
	 if (!vml_int (vmls, "checksum_level", &objp->checksum_level))
		 return FALSE;
	 if (!vml_int (vmls, "exec_task_list", &objp->exec_task_list))
		 return FALSE;
	 if (!vml_Float (vmls, "xi_bare", &objp->xi_bare))
		 return FALSE;
	 if (!vml_int (vmls, "xi_dir", &objp->xi_dir))
		 return FALSE;
	 if (!vml_Float (vmls, "xi_v", &objp->xi_v))
		 return FALSE;
	 if (!vml_Float (vmls, "xi_v_xi", &objp->xi_v_xi))
		 return FALSE;
	 if (!vml_Float (vmls, "clover_coeff", &objp->clover_coeff))
		 return FALSE;
	 if (!vml_Float (vmls, "clover_coeff_xi", &objp->clover_coeff_xi))
		 return FALSE;
	 if (!vml_Float (vmls, "xi_gfix", &objp->xi_gfix))
		 return FALSE;
	 if (!vml_int (vmls, "gfix_chkb", &objp->gfix_chkb))
		 return FALSE;
	 if (!vml_Float (vmls, "asqtad_KS", &objp->asqtad_KS))
		 return FALSE;
	 if (!vml_Float (vmls, "asqtad_naik", &objp->asqtad_naik))
		 return FALSE;
	 if (!vml_Float (vmls, "asqtad_3staple", &objp->asqtad_3staple))
		 return FALSE;
	 if (!vml_Float (vmls, "asqtad_5staple", &objp->asqtad_5staple))
		 return FALSE;
	 if (!vml_Float (vmls, "asqtad_7staple", &objp->asqtad_7staple))
		 return FALSE;
	 if (!vml_Float (vmls, "asqtad_lepage", &objp->asqtad_lepage))
		 return FALSE;
	 if (!vml_Float (vmls, "p4_KS", &objp->p4_KS))
		 return FALSE;
	 if (!vml_Float (vmls, "p4_knight", &objp->p4_knight))
		 return FALSE;
	 if (!vml_Float (vmls, "p4_3staple", &objp->p4_3staple))
		 return FALSE;
	 if (!vml_Float (vmls, "p4_5staple", &objp->p4_5staple))
		 return FALSE;
	 if (!vml_Float (vmls, "p4_7staple", &objp->p4_7staple))
		 return FALSE;
	 if (!vml_Float (vmls, "p4_lepage", &objp->p4_lepage))
		 return FALSE;
	 vml_class_end(vmls,"DoArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
