/*
 * Please do not edit this file.
 * It was generated by CPC make system.
 */
#include <math.h>
#include "alg/do_arg.h"
#if TARGET == QCDOC
#include <qalloc.h>
#endif
CPS_START_NAMESPACE


DoArg::DoArg () {
  x_sites = 0;
  y_sites = 0;
  z_sites = 0;
  t_sites = 0;
  s_sites = 0;
 
  s_node_sites=1;
  s_nodes=1;
  cg_reprod_freq = 0;
  verbose_level=-1202; //RESULT
  checksum_level=0;
  xi_bare=1.0;
  xi_dir=3;
  xi_v=1.0;
  xi_v_xi=1.0;
  clover_coeff=0.0;
  clover_coeff_xi=0.0;
  c_1=0.0;
  u0=1.0;
  xi_gfix=1.0;
  gfix_chkb=1; 
  start_seed_filename = "start_seed";
  start_conf_filename = "start_conf";
#if TARGET == QCDOC
  start_conf_alloc_flag = QFAST|QCOMMS; 
  wfm_send_alloc_flag = QFAST|QCOMMS;
  wfm_alloc_flag = QFAST|QCOMMS;
#else
  wfm_send_alloc_flag = 6;
  wfm_alloc_flag = 6;
  start_conf_alloc_flag = 6; 
#endif
  dwf_a5_inv=1.0;
  power_plaq_cutoff = 0.;
  power_rect_cutoff = 0.;
  asqtad_naik=0.0;
  asqtad_3staple=0.0;
  asqtad_5staple=0.0;
  asqtad_7staple=0.0;
  asqtad_lepage=0.0;
 //  p4_knight=0.0;
//   p4_3staple=0.0;
//   p4_5staple=0.0;
//   p4_7staple=0.0;
//   p4_lepage=0.0;



};
void DoArg::SetupAsqTadU0(double u)
{
  u0 = u;
  asqtad_KS     = (1.0/8.0)+(3.0/8.0)+(1.0/8.0);
  asqtad_naik   = (-1.0/24.0)*pow(u0,-2);
  asqtad_3staple= ( 1.0/16.0)*pow(u0,-4);
  asqtad_5staple= ( 1.0/8.0)*(1.0/8.0)*pow(u0,-4);
  asqtad_7staple= (1.0/8.0)*(1.0/48.0)*pow(u0,-6);
  asqtad_lepage = (-1.0/16.0)*pow(u0,-4);
}
CPS_END_NAMESPACE
