/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/eig_arg.h>
CPS_START_NAMESPACE
	 bool EigArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool EigArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool EigArg::Vml(VML *vmls,char *instance){
		 if(!vml_EigArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_EigArg (VML *vmls, char *name,EigArg *objp)
{
	 vml_class_begin(vmls,"EigArg",name);
	 if (!vml_PatternType (vmls, "pattern_kind", &objp->pattern_kind))
		 return FALSE;
	 if (!vml_Float (vmls, "Mass_init", &objp->Mass_init))
		 return FALSE;
	 if (!vml_Float (vmls, "Mass_final", &objp->Mass_final))
		 return FALSE;
	 if (!vml_Float (vmls, "Mass_step", &objp->Mass_step))
		 return FALSE;
	 if (!vml_array (vmls, "Mass", (char **)&objp->Mass.Mass_val, (u_int *) &objp->Mass.Mass_len, ~0,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_int (vmls, "n_masses", &objp->n_masses))
		 return FALSE;
	 if (!vml_int (vmls, "N_eig", &objp->N_eig))
		 return FALSE;
	 if (!vml_int (vmls, "N_eigacc", &objp->N_eigacc))
		 return FALSE;
	 if (!vml_int (vmls, "Kalk_Sim", &objp->Kalk_Sim))
		 return FALSE;
	 if (!vml_int (vmls, "MaxCG", &objp->MaxCG))
		 return FALSE;
	 if (!vml_Float (vmls, "RsdR_a", &objp->RsdR_a))
		 return FALSE;
	 if (!vml_Float (vmls, "RsdR_r", &objp->RsdR_r))
		 return FALSE;
	 if (!vml_Float (vmls, "Rsdlam", &objp->Rsdlam))
		 return FALSE;
	 if (!vml_Float (vmls, "Cv_fact", &objp->Cv_fact))
		 return FALSE;
	 if (!vml_int (vmls, "N_min", &objp->N_min))
		 return FALSE;
	 if (!vml_int (vmls, "N_max", &objp->N_max))
		 return FALSE;
	 if (!vml_int (vmls, "N_KS_max", &objp->N_KS_max))
		 return FALSE;
	 if (!vml_int (vmls, "n_renorm", &objp->n_renorm))
		 return FALSE;
	 if (!vml_int (vmls, "ProjApsiP", &objp->ProjApsiP))
		 return FALSE;
	 if (!vml_RitzMatType (vmls, "RitzMatOper", &objp->RitzMatOper))
		 return FALSE;
	 if (!vml_int (vmls, "print_hsum", &objp->print_hsum))
		 return FALSE;
	 if (!vml_int (vmls, "hsum_dir", &objp->hsum_dir))
		 return FALSE;
	 if (!vml_Float (vmls, "mass", &objp->mass))
		 return FALSE;
	 if (!vml_string (vmls, "fname", &objp->fname, ~0))
		 return FALSE;
	 if (!vml_int (vmls, "ncorr", &objp->ncorr))
		 return FALSE;
	 vml_class_end(vmls,"EigArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
