/*
 * Please do not edit this file.
 * It was generated by CPC make system.
 */

#include "alg/enum.h"
CPS_START_NAMESPACE

bool_t
vml_Float (VML *vmls, char *name,Float *objp)
{
	register int32_t *buf;

	if (!vml_double (vmls,name,objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_IFloat (VML *vmls, char *name,IFloat *objp)
{
	register int32_t *buf;

	if (!vml_double (vmls,name,objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_DirType (VML *vmls, char *name,DirType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_FclassType (VML *vmls, char *name,FclassType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_GclassType (VML *vmls, char *name,GclassType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_StrOrdType (VML *vmls, char *name,StrOrdType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_CnvFrmType (VML *vmls, char *name,CnvFrmType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_FermionFieldDimension (VML *vmls, char *name,FermionFieldDimension *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_PreserveType (VML *vmls, char *name,PreserveType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_StartConfType (VML *vmls, char *name,StartConfType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_StartSeedType (VML *vmls, char *name,StartSeedType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_ChkbType (VML *vmls, char *name,ChkbType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_DagType (VML *vmls, char *name,DagType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_BndCndType (VML *vmls, char *name,BndCndType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_FixGaugeType (VML *vmls, char *name,FixGaugeType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_SprojType (VML *vmls, char *name,SprojType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_SigmaprojType (VML *vmls, char *name,SigmaprojType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_RitzMatType (VML *vmls, char *name,RitzMatType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_RatApproxType (VML *vmls, char *name,RatApproxType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_MultiShiftSolveType (VML *vmls, char *name,MultiShiftSolveType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_MassRenormaliseDir (VML *vmls, char *name,MassRenormaliseDir *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_FieldType (VML *vmls, char *name,FieldType *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WbaryonFold (VML *vmls, char *name,WbaryonFold *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_SourceKind (VML *vmls, char *name,SourceKind *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_MomentumKind (VML *vmls, char *name,MomentumKind *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_DEVOperatorKind (VML *vmls, char *name,DEVOperatorKind *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WMesonOpKind (VML *vmls, char *name,WMesonOpKind *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WMesonState (VML *vmls, char *name,WMesonState *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WMesonOutputName (VML *vmls, char *name,WMesonOutputName *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WMesonCategory (VML *vmls, char *name,WMesonCategory *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WExtMesonBEOutputName (VML *vmls, char *name,WExtMesonBEOutputName *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WExtMesonBEState (VML *vmls, char *name,WExtMesonBEState *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WExtMesonBEOp (VML *vmls, char *name,WExtMesonBEOp *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_WExtMesonBECategory (VML *vmls, char *name,WExtMesonBECategory *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}

bool_t
vml_FieldTensorId (VML *vmls, char *name,FieldTensorId *objp)
{
	register int32_t *buf;

	if (!vml_enum (vmls,name,(enum_t *)objp))
		return VML_FALSE;
	return VML_TRUE;
}
CPS_END_NAMESPACE
