/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/enum.h>
CPS_START_NAMESPACE

bool_t
vml_pooh (VML *vmls, char *name,pooh *objp)
{
	if (!vml_float (vmls,name,objp))
		return FALSE;
	return TRUE;
}

bool_t
vml_Float (VML *vmls, char *name,Float *objp)
{
	if (!vml_double (vmls,name,objp))
		return FALSE;
	return TRUE;
}

bool_t
vml_IFloat (VML *vmls, char *name,IFloat *objp)
{
	if (!vml_double (vmls,name,objp))
		return FALSE;
	return TRUE;
}

bool_t
vml_Pointer (VML *vmls, char *name,Pointer *objp)
{
	if (!vml_uint64_t (vmls,name,objp))
		return FALSE;
	return TRUE;
}

bool_t
vml_DirType (VML *vmls, char *name,DirType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,DirType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map DirType_map[] = {
	{"DirType","DIR_X",DIR_X},
	{"DirType","DIR_Y",DIR_Y},
	{"DirType","DIR_Z",DIR_Z},
	{"DirType","DIR_T",DIR_T},
	{"DirType","DIR_S",DIR_S},
	{NULL,NULL,0}
};

bool_t
vml_ChiralProj (VML *vmls, char *name,ChiralProj *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,ChiralProj_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map ChiralProj_map[] = {
	{"ChiralProj","PL",PL},
	{"ChiralProj","PR",PR},
	{NULL,NULL,0}
};

bool_t
vml_FclassType (VML *vmls, char *name,FclassType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,FclassType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map FclassType_map[] = {
	{"FclassType","F_CLASS_NONE",F_CLASS_NONE},
	{"FclassType","F_CLASS_STAG",F_CLASS_STAG},
	{"FclassType","F_CLASS_WILSON",F_CLASS_WILSON},
	{"FclassType","F_CLASS_CLOVER",F_CLASS_CLOVER},
	{"FclassType","F_CLASS_DWF",F_CLASS_DWF},
	{"FclassType","F_CLASS_ASQTAD",F_CLASS_ASQTAD},
	{"FclassType","F_CLASS_P4",F_CLASS_P4},
	{"FclassType","F_CLASS_WILSON_TM",F_CLASS_WILSON_TM},
	{"FclassType","F_CLASS_MDWF",F_CLASS_MDWF},
	{"FclassType","F_CLASS_BFM",F_CLASS_BFM},
	{"FclassType","F_CLASS_MOBIUS",F_CLASS_MOBIUS},
	{"FclassType","F_CLASS_NAIVE",F_CLASS_NAIVE},
	{NULL,NULL,0}
};

bool_t
vml_GclassType (VML *vmls, char *name,GclassType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,GclassType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map GclassType_map[] = {
	{"GclassType","G_CLASS_NONE",G_CLASS_NONE},
	{"GclassType","G_CLASS_WILSON",G_CLASS_WILSON},
	{"GclassType","G_CLASS_POWER_PLAQ",G_CLASS_POWER_PLAQ},
	{"GclassType","G_CLASS_IMPR_RECT",G_CLASS_IMPR_RECT},
	{"GclassType","G_CLASS_POWER_RECT",G_CLASS_POWER_RECT},
	{"GclassType","G_CLASS_IMPR_OLSYM",G_CLASS_IMPR_OLSYM},
	{"GclassType","G_CLASS_TADPOLE_RECT",G_CLASS_TADPOLE_RECT},
	{NULL,NULL,0}
};

bool_t
vml_StrOrdType (VML *vmls, char *name,StrOrdType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,StrOrdType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map StrOrdType_map[] = {
	{"StrOrdType","CANONICAL",CANONICAL},
	{"StrOrdType","STAG",STAG},
	{"StrOrdType","WILSON",WILSON},
	{"StrOrdType","G_WILSON_HB",G_WILSON_HB},
	{"StrOrdType","STAG_BLOCK",STAG_BLOCK},
	{"StrOrdType","DWF_5D_EOPREC",DWF_5D_EOPREC},
	{"StrOrdType","DWF_4D_EOPREC",DWF_4D_EOPREC},
	{"StrOrdType","DWF_4D_EOPREC_EE",DWF_4D_EOPREC_EE},
	{NULL,NULL,0}
};

bool_t
vml_CnvFrmType (VML *vmls, char *name,CnvFrmType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,CnvFrmType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map CnvFrmType_map[] = {
	{"CnvFrmType","CNV_FRM_NO",CNV_FRM_NO},
	{"CnvFrmType","CNV_FRM_YES",CNV_FRM_YES},
	{NULL,NULL,0}
};

bool_t
vml_FermionFieldDimension (VML *vmls, char *name,FermionFieldDimension *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,FermionFieldDimension_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map FermionFieldDimension_map[] = {
	{"FermionFieldDimension","FOUR_D",FOUR_D},
	{"FermionFieldDimension","FIVE_D",FIVE_D},
	{NULL,NULL,0}
};

bool_t
vml_PreserveType (VML *vmls, char *name,PreserveType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,PreserveType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map PreserveType_map[] = {
	{"PreserveType","PRESERVE_NO",PRESERVE_NO},
	{"PreserveType","PRESERVE_YES",PRESERVE_YES},
	{NULL,NULL,0}
};

bool_t
vml_StartConfType (VML *vmls, char *name,StartConfType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,StartConfType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map StartConfType_map[] = {
	{"StartConfType","START_CONF_ORD",START_CONF_ORD},
	{"StartConfType","START_CONF_DISORD",START_CONF_DISORD},
	{"StartConfType","START_CONF_FILE",START_CONF_FILE},
	{"StartConfType","START_CONF_LOAD",START_CONF_LOAD},
	{"StartConfType","START_CONF_MEM",START_CONF_MEM},
	{NULL,NULL,0}
};

bool_t
vml_StartSeedType (VML *vmls, char *name,StartSeedType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,StartSeedType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map StartSeedType_map[] = {
	{"StartSeedType","START_SEED_FIXED",START_SEED_FIXED},
	{"StartSeedType","START_SEED_FIXED_UNIFORM",START_SEED_FIXED_UNIFORM},
	{"StartSeedType","START_SEED",START_SEED},
	{"StartSeedType","START_SEED_UNIFORM",START_SEED_UNIFORM},
	{"StartSeedType","START_SEED_INPUT",START_SEED_INPUT},
	{"StartSeedType","START_SEED_INPUT_UNIFORM",START_SEED_INPUT_UNIFORM},
	{"StartSeedType","START_SEED_INPUT_NODE",START_SEED_INPUT_NODE},
	{"StartSeedType","START_SEED_FILE",START_SEED_FILE},
	{NULL,NULL,0}
};

bool_t
vml_ChkbType (VML *vmls, char *name,ChkbType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,ChkbType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map ChkbType_map[] = {
	{"ChkbType","CHKB_EVEN",CHKB_EVEN},
	{"ChkbType","CHKB_ODD",CHKB_ODD},
	{NULL,NULL,0}
};

bool_t
vml_DagType (VML *vmls, char *name,DagType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,DagType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map DagType_map[] = {
	{"DagType","DAG_NO",DAG_NO},
	{"DagType","DAG_YES",DAG_YES},
	{NULL,NULL,0}
};

bool_t
vml_BndCndType (VML *vmls, char *name,BndCndType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,BndCndType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map BndCndType_map[] = {
	{"BndCndType","BND_CND_PRD",BND_CND_PRD},
	{"BndCndType","BND_CND_APRD",BND_CND_APRD},
	{NULL,NULL,0}
};

bool_t
vml_FixGaugeType (VML *vmls, char *name,FixGaugeType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,FixGaugeType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map FixGaugeType_map[] = {
	{"FixGaugeType","FIX_GAUGE_NONE",FIX_GAUGE_NONE},
	{"FixGaugeType","FIX_GAUGE_LANDAU",FIX_GAUGE_LANDAU},
	{"FixGaugeType","FIX_GAUGE_COULOMB_X",FIX_GAUGE_COULOMB_X},
	{"FixGaugeType","FIX_GAUGE_COULOMB_Y",FIX_GAUGE_COULOMB_Y},
	{"FixGaugeType","FIX_GAUGE_COULOMB_Z",FIX_GAUGE_COULOMB_Z},
	{"FixGaugeType","FIX_GAUGE_COULOMB_T",FIX_GAUGE_COULOMB_T},
	{NULL,NULL,0}
};

bool_t
vml_SprojType (VML *vmls, char *name,SprojType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,SprojType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map SprojType_map[] = {
	{"SprojType","SPROJ_XM",SPROJ_XM},
	{"SprojType","SPROJ_YM",SPROJ_YM},
	{"SprojType","SPROJ_ZM",SPROJ_ZM},
	{"SprojType","SPROJ_TM",SPROJ_TM},
	{"SprojType","SPROJ_XP",SPROJ_XP},
	{"SprojType","SPROJ_YP",SPROJ_YP},
	{"SprojType","SPROJ_ZP",SPROJ_ZP},
	{"SprojType","SPROJ_TP",SPROJ_TP},
	{NULL,NULL,0}
};

bool_t
vml_SigmaprojType (VML *vmls, char *name,SigmaprojType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,SigmaprojType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map SigmaprojType_map[] = {
	{"SigmaprojType","SIGMAPROJ_XY",SIGMAPROJ_XY},
	{"SigmaprojType","SIGMAPROJ_XZ",SIGMAPROJ_XZ},
	{"SigmaprojType","SIGMAPROJ_XT",SIGMAPROJ_XT},
	{"SigmaprojType","SIGMAPROJ_YZ",SIGMAPROJ_YZ},
	{"SigmaprojType","SIGMAPROJ_YT",SIGMAPROJ_YT},
	{"SigmaprojType","SIGMAPROJ_YX",SIGMAPROJ_YX},
	{"SigmaprojType","SIGMAPROJ_ZT",SIGMAPROJ_ZT},
	{"SigmaprojType","SIGMAPROJ_ZX",SIGMAPROJ_ZX},
	{"SigmaprojType","SIGMAPROJ_ZY",SIGMAPROJ_ZY},
	{"SigmaprojType","SIGMAPROJ_TX",SIGMAPROJ_TX},
	{"SigmaprojType","SIGMAPROJ_TY",SIGMAPROJ_TY},
	{"SigmaprojType","SIGMAPROJ_TZ",SIGMAPROJ_TZ},
	{NULL,NULL,0}
};

bool_t
vml_RitzMatType (VML *vmls, char *name,RitzMatType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,RitzMatType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map RitzMatType_map[] = {
	{"RitzMatType","NONE",NONE},
	{"RitzMatType","MAT_HERM",MAT_HERM},
	{"RitzMatType","MATPC_HERM",MATPC_HERM},
	{"RitzMatType","MATPCDAG_MATPC",MATPCDAG_MATPC},
	{"RitzMatType","NEG_MATPCDAG_MATPC",NEG_MATPCDAG_MATPC},
	{"RitzMatType","MATDAG_MAT",MATDAG_MAT},
	{"RitzMatType","NEG_MATDAG_MAT",NEG_MATDAG_MAT},
	{"RitzMatType","MATDAG_MAT_NORM",MATDAG_MAT_NORM},
	{"RitzMatType","NEG_MATDAG_MAT_NORM",NEG_MATDAG_MAT_NORM},
	{"RitzMatType","MATPCDAG_MATPC_SHIFT",MATPCDAG_MATPC_SHIFT},
	{"RitzMatType","RitzMatType_LAST",RitzMatType_LAST},
	{NULL,NULL,0}
};

bool_t
vml_RatApproxType (VML *vmls, char *name,RatApproxType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,RatApproxType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map RatApproxType_map[] = {
	{"RatApproxType","CONSTANT",CONSTANT},
	{"RatApproxType","DYNAMIC",DYNAMIC},
	{NULL,NULL,0}
};

bool_t
vml_MultiShiftSolveType (VML *vmls, char *name,MultiShiftSolveType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,MultiShiftSolveType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map MultiShiftSolveType_map[] = {
	{"MultiShiftSolveType","SINGLE",SINGLE},
	{"MultiShiftSolveType","MULTI",MULTI},
	{"MultiShiftSolveType","GENERAL",GENERAL},
	{NULL,NULL,0}
};

bool_t
vml_MassRenormaliseDir (VML *vmls, char *name,MassRenormaliseDir *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,MassRenormaliseDir_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map MassRenormaliseDir_map[] = {
	{"MassRenormaliseDir","RENORM_BACKWARDS",RENORM_BACKWARDS},
	{"MassRenormaliseDir","RENORM_FORWARDS",RENORM_FORWARDS},
	{NULL,NULL,0}
};

bool_t
vml_FieldType (VML *vmls, char *name,FieldType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,FieldType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map FieldType_map[] = {
	{"FieldType","FERMION",FERMION},
	{"FieldType","BOSON",BOSON},
	{NULL,NULL,0}
};

bool_t
vml_RatType (VML *vmls, char *name,RatType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,RatType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map RatType_map[] = {
	{"RatType","RATIONAL_STANDARD",RATIONAL_STANDARD},
	{"RatType","RATIONAL_QUOTIENT",RATIONAL_QUOTIENT},
	{"RatType","RATIONAL_SPLIT",RATIONAL_SPLIT},
	{NULL,NULL,0}
};

bool_t
vml_WbaryonFold (VML *vmls, char *name,WbaryonFold *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WbaryonFold_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WbaryonFold_map[] = {
	{"WbaryonFold","BARYON_FOLD",BARYON_FOLD},
	{"WbaryonFold","BARYON_RAW",BARYON_RAW},
	{"WbaryonFold","BARYON_PAST",BARYON_PAST},
	{NULL,NULL,0}
};

bool_t
vml_SourceKind (VML *vmls, char *name,SourceKind *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,SourceKind_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map SourceKind_map[] = {
	{"SourceKind","POINT_W",POINT_W},
	{"SourceKind","WALL_W",WALL_W},
	{"SourceKind","BOX_W",BOX_W},
	{"SourceKind","JACOBI_W",JACOBI_W},
	{"SourceKind","MAX_NUM_SINK",MAX_NUM_SINK},
	{"SourceKind","Z2",Z2},
	{"SourceKind","COMPLEX_Z2",COMPLEX_Z2},
	{"SourceKind","KURAMASHI",KURAMASHI},
	{NULL,NULL,0}
};

bool_t
vml_SinkKind (VML *vmls, char *name,SinkKind *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,SinkKind_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map SinkKind_map[] = {
	{"SinkKind","W_POINT",W_POINT},
	{"SinkKind","W_WALL",W_WALL},
	{"SinkKind","W_BOX",W_BOX},
	{NULL,NULL,0}
};

bool_t
vml_MomentumKind (VML *vmls, char *name,MomentumKind *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,MomentumKind_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map MomentumKind_map[] = {
	{"MomentumKind","MOM_000",MOM_000},
	{"MomentumKind","MOM_001",MOM_001},
	{"MomentumKind","MOM_002",MOM_002},
	{"MomentumKind","MOM_011",MOM_011},
	{"MomentumKind","MOM_022",MOM_022},
	{"MomentumKind","MOM_111",MOM_111},
	{"MomentumKind","MOM_222",MOM_222},
	{"MomentumKind","MAX_NUM_MOMENTA",MAX_NUM_MOMENTA},
	{NULL,NULL,0}
};

bool_t
vml_DEVOperatorKind (VML *vmls, char *name,DEVOperatorKind *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,DEVOperatorKind_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map DEVOperatorKind_map[] = {
	{"DEVOperatorKind","UNIT",UNIT},
	{"DEVOperatorKind","DEV1",DEV1},
	{"DEVOperatorKind","DEV2",DEV2},
	{"DEVOperatorKind","DEV3",DEV3},
	{"DEVOperatorKind","DEV1DEV2",DEV1DEV2},
	{"DEVOperatorKind","DEV2DEV1",DEV2DEV1},
	{"DEVOperatorKind","DEV2DEV3",DEV2DEV3},
	{"DEVOperatorKind","DEV3DEV2",DEV3DEV2},
	{"DEVOperatorKind","DEV1DEV3",DEV1DEV3},
	{"DEVOperatorKind","DEV3DEV1",DEV3DEV1},
	{"DEVOperatorKind","DEV1DEV1",DEV1DEV1},
	{"DEVOperatorKind","DEV2DEV2",DEV2DEV2},
	{"DEVOperatorKind","DEV3DEV3",DEV3DEV3},
	{"DEVOperatorKind","DEV_OP_NUM",DEV_OP_NUM},
	{"DEVOperatorKind","SUM_F",SUM_F},
	{"DEVOperatorKind","SUM_S_ANTISYM",SUM_S_ANTISYM},
	{"DEVOperatorKind","SUM_S_SYM",SUM_S_SYM},
	{"DEVOperatorKind","SUM_S_DIAG",SUM_S_DIAG},
	{"DEVOperatorKind","SUM_F_S_ANTISYM",SUM_F_S_ANTISYM},
	{"DEVOperatorKind","SUM_S_SYM_DIAG",SUM_S_SYM_DIAG},
	{"DEVOperatorKind","SUM_UNIT_F_S_ANTISYM",SUM_UNIT_F_S_ANTISYM},
	{"DEVOperatorKind","END_SUM_OP",END_SUM_OP},
	{"DEVOperatorKind","BEGIN_BE_OP",BEGIN_BE_OP},
	{"DEVOperatorKind","FB1_OP",FB1_OP},
	{"DEVOperatorKind","FB2_OP",FB2_OP},
	{"DEVOperatorKind","FB3_OP",FB3_OP},
	{"DEVOperatorKind","FE1_OP",FE1_OP},
	{"DEVOperatorKind","FE2_OP",FE2_OP},
	{"DEVOperatorKind","FE3_OP",FE3_OP},
	{"DEVOperatorKind","FUNIT_OP",FUNIT_OP},
	{"DEVOperatorKind","SUM_MAGN_OP",SUM_MAGN_OP},
	{"DEVOperatorKind","SUM_ELEC_OP",SUM_ELEC_OP},
	{"DEVOperatorKind","SUM_MAGN_ELEC_OP",SUM_MAGN_ELEC_OP},
	{"DEVOperatorKind","END_BE_OP",END_BE_OP},
	{NULL,NULL,0}
};

bool_t
vml_WMesonOpKind (VML *vmls, char *name,WMesonOpKind *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WMesonOpKind_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WMesonOpKind_map[] = {
	{"WMesonOpKind","MO_a0xP_x",MO_a0xP_x},
	{"WMesonOpKind","MO_a0xP_y",MO_a0xP_y},
	{"WMesonOpKind","MO_a0xP_z",MO_a0xP_z},
	{"WMesonOpKind","MO_pionxP_x",MO_pionxP_x},
	{"WMesonOpKind","MO_pionxP_y",MO_pionxP_y},
	{"WMesonOpKind","MO_pionxP_z",MO_pionxP_z},
	{"WMesonOpKind","MO_a0_primexP_x",MO_a0_primexP_x},
	{"WMesonOpKind","MO_a0_primexP_y",MO_a0_primexP_y},
	{"WMesonOpKind","MO_a0_primexP_z",MO_a0_primexP_z},
	{"WMesonOpKind","MO_rhoxP_A1",MO_rhoxP_A1},
	{"WMesonOpKind","MO_rhoxP_T1_x",MO_rhoxP_T1_x},
	{"WMesonOpKind","MO_rhoxP_T1_y",MO_rhoxP_T1_y},
	{"WMesonOpKind","MO_rhoxP_T1_z",MO_rhoxP_T1_z},
	{"WMesonOpKind","MO_rhoxP_T2_x",MO_rhoxP_T2_x},
	{"WMesonOpKind","MO_rhoxP_T2_y",MO_rhoxP_T2_y},
	{"WMesonOpKind","MO_rhoxP_T2_z",MO_rhoxP_T2_z},
	{"WMesonOpKind","MO_a1xP_A1",MO_a1xP_A1},
	{"WMesonOpKind","MO_a1xP_T2_x",MO_a1xP_T2_x},
	{"WMesonOpKind","MO_a1xP_T2_y",MO_a1xP_T2_y},
	{"WMesonOpKind","MO_a1xP_T2_z",MO_a1xP_T2_z},
	{"WMesonOpKind","MO_a1xP_E_1",MO_a1xP_E_1},
	{"WMesonOpKind","MO_a1xP_E_2",MO_a1xP_E_2},
	{"WMesonOpKind","MO_b1xP_T1_x",MO_b1xP_T1_x},
	{"WMesonOpKind","MO_b1xP_T1_y",MO_b1xP_T1_y},
	{"WMesonOpKind","MO_b1xP_T1_z",MO_b1xP_T1_z},
	{"WMesonOpKind","MO_b1xD_A2",MO_b1xD_A2},
	{"WMesonOpKind","MO_b1xD_T1_x",MO_b1xD_T1_x},
	{"WMesonOpKind","MO_b1xD_T1_y",MO_b1xD_T1_y},
	{"WMesonOpKind","MO_b1xD_T1_z",MO_b1xD_T1_z},
	{"WMesonOpKind","MO_b1xD_T2_x",MO_b1xD_T2_x},
	{"WMesonOpKind","MO_b1xD_T2_y",MO_b1xD_T2_y},
	{"WMesonOpKind","MO_b1xD_T2_z",MO_b1xD_T2_z},
	{"WMesonOpKind","MO_b1xD_E_1",MO_b1xD_E_1},
	{"WMesonOpKind","MO_b1xD_E_2",MO_b1xD_E_2},
	{"WMesonOpKind","MO_a0_primexD_x",MO_a0_primexD_x},
	{"WMesonOpKind","MO_a0_primexD_y",MO_a0_primexD_y},
	{"WMesonOpKind","MO_a0_primexD_z",MO_a0_primexD_z},
	{"WMesonOpKind","MO_rhoxB_T1_x",MO_rhoxB_T1_x},
	{"WMesonOpKind","MO_rhoxB_T1_y",MO_rhoxB_T1_y},
	{"WMesonOpKind","MO_rhoxB_T1_z",MO_rhoxB_T1_z},
	{"WMesonOpKind","MO_rhoxB_T2_x",MO_rhoxB_T2_x},
	{"WMesonOpKind","MO_rhoxB_T2_y",MO_rhoxB_T2_y},
	{"WMesonOpKind","MO_rhoxB_T2_z",MO_rhoxB_T2_z},
	{"WMesonOpKind","MO_a1xB_A1",MO_a1xB_A1},
	{"WMesonOpKind","MO_a1xB_T1_x",MO_a1xB_T1_x},
	{"WMesonOpKind","MO_a1xB_T1_y",MO_a1xB_T1_y},
	{"WMesonOpKind","MO_a1xB_T1_z",MO_a1xB_T1_z},
	{"WMesonOpKind","MO_a1xB_T2_x",MO_a1xB_T2_x},
	{"WMesonOpKind","MO_a1xB_T2_y",MO_a1xB_T2_y},
	{"WMesonOpKind","MO_a1xB_T2_z",MO_a1xB_T2_z},
	{"WMesonOpKind","MO_a1xD_A2",MO_a1xD_A2},
	{"WMesonOpKind","MO_a1xD_T1_x",MO_a1xD_T1_x},
	{"WMesonOpKind","MO_a1xD_T1_y",MO_a1xD_T1_y},
	{"WMesonOpKind","MO_a1xD_T1_z",MO_a1xD_T1_z},
	{"WMesonOpKind","MO_a1xD_T2_x",MO_a1xD_T2_x},
	{"WMesonOpKind","MO_a1xD_T2_y",MO_a1xD_T2_y},
	{"WMesonOpKind","MO_a1xD_T2_z",MO_a1xD_T2_z},
	{"WMesonOpKind","MO_a1xD_E_1",MO_a1xD_E_1},
	{"WMesonOpKind","MO_a1xD_E_2",MO_a1xD_E_2},
	{"WMesonOpKind","MO_rhoxD_A2",MO_rhoxD_A2},
	{"WMesonOpKind","MO_rhoxD_T1_x",MO_rhoxD_T1_x},
	{"WMesonOpKind","MO_rhoxD_T1_y",MO_rhoxD_T1_y},
	{"WMesonOpKind","MO_rhoxD_T1_z",MO_rhoxD_T1_z},
	{"WMesonOpKind","MO_rhoxD_T2_x",MO_rhoxD_T2_x},
	{"WMesonOpKind","MO_rhoxD_T2_y",MO_rhoxD_T2_y},
	{"WMesonOpKind","MO_rhoxD_T2_z",MO_rhoxD_T2_z},
	{"WMesonOpKind","MO_pionxB_T1_x",MO_pionxB_T1_x},
	{"WMesonOpKind","MO_pionxB_T1_y",MO_pionxB_T1_y},
	{"WMesonOpKind","MO_pionxB_T1_z",MO_pionxB_T1_z},
	{"WMesonOpKind","MO_pionxD_T2_x",MO_pionxD_T2_x},
	{"WMesonOpKind","MO_pionxD_T2_y",MO_pionxD_T2_y},
	{"WMesonOpKind","MO_pionxD_T2_z",MO_pionxD_T2_z},
	{"WMesonOpKind","NUM_WMESON_OP_KIND",NUM_WMESON_OP_KIND},
	{NULL,NULL,0}
};

bool_t
vml_WMesonState (VML *vmls, char *name,WMesonState *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WMesonState_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WMesonState_map[] = {
	{"WMesonState","MS_a0xP_x",MS_a0xP_x},
	{"WMesonState","MS_a0xP_y",MS_a0xP_y},
	{"WMesonState","MS_a0xP_z",MS_a0xP_z},
	{"WMesonState","MS_pionxP_x",MS_pionxP_x},
	{"WMesonState","MS_pionxP_y",MS_pionxP_y},
	{"WMesonState","MS_pionxP_z",MS_pionxP_z},
	{"WMesonState","MS_a0_primexP_x",MS_a0_primexP_x},
	{"WMesonState","MS_a0_primexP_y",MS_a0_primexP_y},
	{"WMesonState","MS_a0_primexP_z",MS_a0_primexP_z},
	{"WMesonState","MS_rhoxP_A1_1",MS_rhoxP_A1_1},
	{"WMesonState","MS_rhoxP_T1_x",MS_rhoxP_T1_x},
	{"WMesonState","MS_rhoxP_T1_y",MS_rhoxP_T1_y},
	{"WMesonState","MS_rhoxP_T1_z",MS_rhoxP_T1_z},
	{"WMesonState","MS_rhoxP_T2_x",MS_rhoxP_T2_x},
	{"WMesonState","MS_rhoxP_T2_y",MS_rhoxP_T2_y},
	{"WMesonState","MS_rhoxP_T2_z",MS_rhoxP_T2_z},
	{"WMesonState","MS_a1xP_A1_1",MS_a1xP_A1_1},
	{"WMesonState","MS_a1xP_T2_x",MS_a1xP_T2_x},
	{"WMesonState","MS_a1xP_T2_y",MS_a1xP_T2_y},
	{"WMesonState","MS_a1xP_T2_z",MS_a1xP_T2_z},
	{"WMesonState","MS_a1xP_E_1",MS_a1xP_E_1},
	{"WMesonState","MS_a1xP_E_2",MS_a1xP_E_2},
	{"WMesonState","MS_b1xP_T1_x",MS_b1xP_T1_x},
	{"WMesonState","MS_b1xP_T1_y",MS_b1xP_T1_y},
	{"WMesonState","MS_b1xP_T1_z",MS_b1xP_T1_z},
	{"WMesonState","MS_b1xD_A2_1",MS_b1xD_A2_1},
	{"WMesonState","MS_b1xD_T1_x",MS_b1xD_T1_x},
	{"WMesonState","MS_b1xD_T1_y",MS_b1xD_T1_y},
	{"WMesonState","MS_b1xD_T1_z",MS_b1xD_T1_z},
	{"WMesonState","MS_b1xD_T2_x",MS_b1xD_T2_x},
	{"WMesonState","MS_b1xD_T2_y",MS_b1xD_T2_y},
	{"WMesonState","MS_b1xD_T2_z",MS_b1xD_T2_z},
	{"WMesonState","MS_b1xD_E_1",MS_b1xD_E_1},
	{"WMesonState","MS_b1xD_E_2",MS_b1xD_E_2},
	{"WMesonState","MS_a0_primexD_x",MS_a0_primexD_x},
	{"WMesonState","MS_a0_primexD_y",MS_a0_primexD_y},
	{"WMesonState","MS_a0_primexD_z",MS_a0_primexD_z},
	{"WMesonState","MS_rhoxB_T1_x",MS_rhoxB_T1_x},
	{"WMesonState","MS_rhoxB_T1_y",MS_rhoxB_T1_y},
	{"WMesonState","MS_rhoxB_T1_z",MS_rhoxB_T1_z},
	{"WMesonState","MS_rhoxB_T2_x",MS_rhoxB_T2_x},
	{"WMesonState","MS_rhoxB_T2_y",MS_rhoxB_T2_y},
	{"WMesonState","MS_rhoxB_T2_z",MS_rhoxB_T2_z},
	{"WMesonState","MS_a1xB_A1_1",MS_a1xB_A1_1},
	{"WMesonState","MS_a1xB_T1_x",MS_a1xB_T1_x},
	{"WMesonState","MS_a1xB_T1_y",MS_a1xB_T1_y},
	{"WMesonState","MS_a1xB_T1_z",MS_a1xB_T1_z},
	{"WMesonState","MS_a1xB_T2_x",MS_a1xB_T2_x},
	{"WMesonState","MS_a1xB_T2_y",MS_a1xB_T2_y},
	{"WMesonState","MS_a1xB_T2_z",MS_a1xB_T2_z},
	{"WMesonState","MS_a1xD_A2_1",MS_a1xD_A2_1},
	{"WMesonState","MS_a1xD_T1_x",MS_a1xD_T1_x},
	{"WMesonState","MS_a1xD_T1_y",MS_a1xD_T1_y},
	{"WMesonState","MS_a1xD_T1_z",MS_a1xD_T1_z},
	{"WMesonState","MS_a1xD_T2_x",MS_a1xD_T2_x},
	{"WMesonState","MS_a1xD_T2_y",MS_a1xD_T2_y},
	{"WMesonState","MS_a1xD_T2_z",MS_a1xD_T2_z},
	{"WMesonState","MS_a1xD_E_1",MS_a1xD_E_1},
	{"WMesonState","MS_a1xD_E_2",MS_a1xD_E_2},
	{"WMesonState","MS_rhoxD_A2_1",MS_rhoxD_A2_1},
	{"WMesonState","MS_rhoxD_T1_x",MS_rhoxD_T1_x},
	{"WMesonState","MS_rhoxD_T1_y",MS_rhoxD_T1_y},
	{"WMesonState","MS_rhoxD_T1_z",MS_rhoxD_T1_z},
	{"WMesonState","MS_rhoxD_T2_x",MS_rhoxD_T2_x},
	{"WMesonState","MS_rhoxD_T2_y",MS_rhoxD_T2_y},
	{"WMesonState","MS_rhoxD_T2_z",MS_rhoxD_T2_z},
	{"WMesonState","MS_pionxB_T1_x",MS_pionxB_T1_x},
	{"WMesonState","MS_pionxB_T1_y",MS_pionxB_T1_y},
	{"WMesonState","MS_pionxB_T1_z",MS_pionxB_T1_z},
	{"WMesonState","MS_pionxD_T2_x",MS_pionxD_T2_x},
	{"WMesonState","MS_pionxD_T2_y",MS_pionxD_T2_y},
	{"WMesonState","MS_pionxD_T2_z",MS_pionxD_T2_z},
	{"WMesonState","NUM_WMESON_STATE",NUM_WMESON_STATE},
	{NULL,NULL,0}
};

bool_t
vml_WMesonOutputName (VML *vmls, char *name,WMesonOutputName *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WMesonOutputName_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WMesonOutputName_map[] = {
	{"WMesonOutputName","a0xP",a0xP},
	{"WMesonOutputName","pionxP",pionxP},
	{"WMesonOutputName","a0_primexP",a0_primexP},
	{"WMesonOutputName","rhoxP_A1",rhoxP_A1},
	{"WMesonOutputName","rhoxP_T1",rhoxP_T1},
	{"WMesonOutputName","rhoxP_T2",rhoxP_T2},
	{"WMesonOutputName","a1xP_A1",a1xP_A1},
	{"WMesonOutputName","a1xP_T2",a1xP_T2},
	{"WMesonOutputName","a1xP_E",a1xP_E},
	{"WMesonOutputName","b1xP_T1",b1xP_T1},
	{"WMesonOutputName","b1xD_A2",b1xD_A2},
	{"WMesonOutputName","b1xD_T1",b1xD_T1},
	{"WMesonOutputName","b1xD_T2",b1xD_T2},
	{"WMesonOutputName","b1xD_E",b1xD_E},
	{"WMesonOutputName","a0_primexD",a0_primexD},
	{"WMesonOutputName","rhoxB_T1",rhoxB_T1},
	{"WMesonOutputName","rhoxB_T2",rhoxB_T2},
	{"WMesonOutputName","a1xB_A1",a1xB_A1},
	{"WMesonOutputName","a1xB_T1",a1xB_T1},
	{"WMesonOutputName","a1xB_T2",a1xB_T2},
	{"WMesonOutputName","a1xD_A2",a1xD_A2},
	{"WMesonOutputName","a1xD_T1",a1xD_T1},
	{"WMesonOutputName","a1xD_T2",a1xD_T2},
	{"WMesonOutputName","a1xD_E",a1xD_E},
	{"WMesonOutputName","rhoxD_A2",rhoxD_A2},
	{"WMesonOutputName","rhoxD_T1",rhoxD_T1},
	{"WMesonOutputName","rhoxD_T2",rhoxD_T2},
	{"WMesonOutputName","pionxB_T1",pionxB_T1},
	{"WMesonOutputName","pionxD_T2",pionxD_T2},
	{"WMesonOutputName","NUM_WMESON_OUTPUT",NUM_WMESON_OUTPUT},
	{NULL,NULL,0}
};

bool_t
vml_WMesonCategory (VML *vmls, char *name,WMesonCategory *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WMesonCategory_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WMesonCategory_map[] = {
	{"WMesonCategory","NORMALMESON",NORMALMESON},
	{"WMesonCategory","EXT_FIRSTDEV_MESON",EXT_FIRSTDEV_MESON},
	{"WMesonCategory","EXT_SECONDDEV_SYM_MESON",EXT_SECONDDEV_SYM_MESON},
	{"WMesonCategory","EXT_SECONDDEV_ANTISYM_MESON",EXT_SECONDDEV_ANTISYM_MESON},
	{"WMesonCategory","EXT_SECONDDEV_DIAG_MESON",EXT_SECONDDEV_DIAG_MESON},
	{"WMesonCategory","MIXING",MIXING},
	{NULL,NULL,0}
};

bool_t
vml_WExtMesonBEOutputName (VML *vmls, char *name,WExtMesonBEOutputName *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WExtMesonBEOutputName_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WExtMesonBEOutputName_map[] = {
	{"WExtMesonBEOutputName","BE_pionxB",BE_pionxB},
	{"WExtMesonBEOutputName","BE_rhoxB_T1",BE_rhoxB_T1},
	{"WExtMesonBEOutputName","NUM_WEXTMESON_BE_OUTPUT",NUM_WEXTMESON_BE_OUTPUT},
	{NULL,NULL,0}
};

bool_t
vml_WExtMesonBEState (VML *vmls, char *name,WExtMesonBEState *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WExtMesonBEState_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WExtMesonBEState_map[] = {
	{"WExtMesonBEState","BE_MS_pionxB_x",BE_MS_pionxB_x},
	{"WExtMesonBEState","BE_MS_pionxB_y",BE_MS_pionxB_y},
	{"WExtMesonBEState","BE_MS_pionxB_z",BE_MS_pionxB_z},
	{"WExtMesonBEState","BE_MS_rhoxB_T1_x",BE_MS_rhoxB_T1_x},
	{"WExtMesonBEState","BE_MS_rhoxB_T1_y",BE_MS_rhoxB_T1_y},
	{"WExtMesonBEState","BE_MS_rhoxB_T1_z",BE_MS_rhoxB_T1_z},
	{"WExtMesonBEState","NUM_WEXTMESON_BE_STATES",NUM_WEXTMESON_BE_STATES},
	{NULL,NULL,0}
};

bool_t
vml_WExtMesonBEOp (VML *vmls, char *name,WExtMesonBEOp *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WExtMesonBEOp_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WExtMesonBEOp_map[] = {
	{"WExtMesonBEOp","BE_MO_pionxB_x",BE_MO_pionxB_x},
	{"WExtMesonBEOp","BE_MO_pionxB_y",BE_MO_pionxB_y},
	{"WExtMesonBEOp","BE_MO_pionxB_z",BE_MO_pionxB_z},
	{"WExtMesonBEOp","BE_MO_rhoxB_T1_x",BE_MO_rhoxB_T1_x},
	{"WExtMesonBEOp","BE_MO_rhoxB_T1_y",BE_MO_rhoxB_T1_y},
	{"WExtMesonBEOp","BE_MO_rhoxB_T1_z",BE_MO_rhoxB_T1_z},
	{"WExtMesonBEOp","NUM_WEXTMESON_BE_OPS",NUM_WEXTMESON_BE_OPS},
	{NULL,NULL,0}
};

bool_t
vml_WExtMesonBECategory (VML *vmls, char *name,WExtMesonBECategory *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,WExtMesonBECategory_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map WExtMesonBECategory_map[] = {
	{"WExtMesonBECategory","ELEC_HYBRID_BE",ELEC_HYBRID_BE},
	{"WExtMesonBECategory","MAG_HYBRID_BE",MAG_HYBRID_BE},
	{"WExtMesonBECategory","MIXING_BE",MIXING_BE},
	{NULL,NULL,0}
};

bool_t
vml_FieldTensorId (VML *vmls, char *name,FieldTensorId *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,FieldTensorId_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map FieldTensorId_map[] = {
	{"FieldTensorId","FB1",FB1},
	{"FieldTensorId","FB2",FB2},
	{"FieldTensorId","FB3",FB3},
	{"FieldTensorId","FE1",FE1},
	{"FieldTensorId","FE2",FE2},
	{"FieldTensorId","FE3",FE3},
	{"FieldTensorId","NUM_FLDS",NUM_FLDS},
	{"FieldTensorId","FUNIT",FUNIT},
	{"FieldTensorId","SUM_MAGN",SUM_MAGN},
	{"FieldTensorId","SUM_ELEC",SUM_ELEC},
	{"FieldTensorId","SUM_MAGN_ELEC",SUM_MAGN_ELEC},
	{"FieldTensorId","NUM_FLD_OPS",NUM_FLD_OPS},
	{NULL,NULL,0}
};

bool_t
vml_PatternType (VML *vmls, char *name,PatternType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,PatternType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map PatternType_map[] = {
	{"PatternType","LIN",LIN},
	{"PatternType","ARRAY",ARRAY},
	{"PatternType","LOG",LOG},
	{"PatternType","FLOW",FLOW},
	{NULL,NULL,0}
};

bool_t
vml_IntegratorType (VML *vmls, char *name,IntegratorType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,IntegratorType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map IntegratorType_map[] = {
	{"IntegratorType","INT_LEAP",INT_LEAP},
	{"IntegratorType","INT_OMELYAN",INT_OMELYAN},
	{"IntegratorType","INT_CAMPOSTRINI",INT_CAMPOSTRINI},
	{"IntegratorType","INT_OMELYAN_44",INT_OMELYAN_44},
	{"IntegratorType","INT_OMELYAN_45",INT_OMELYAN_45},
	{"IntegratorType","INT_FORCE_GRAD_PQPQP",INT_FORCE_GRAD_PQPQP},
	{"IntegratorType","INT_FORCE_GRAD_QPQPQ",INT_FORCE_GRAD_QPQPQ},
	{"IntegratorType","INT_FORCE_GRAD_QPQPQPQ",INT_FORCE_GRAD_QPQPQPQ},
	{"IntegratorType","INT_FORCE_GRAD_PQPQPQPQP",INT_FORCE_GRAD_PQPQPQPQP},
	{"IntegratorType","INT_SUM",INT_SUM},
	{"IntegratorType","INT_MOM",INT_MOM},
	{"IntegratorType","INT_GAUGE",INT_GAUGE},
	{"IntegratorType","INT_FERMION",INT_FERMION},
	{"IntegratorType","INT_BOSON",INT_BOSON},
	{"IntegratorType","INT_QUOTIENT",INT_QUOTIENT},
	{"IntegratorType","INT_RATIONAL",INT_RATIONAL},
	{"IntegratorType","INT_RATIONAL_SPLIT",INT_RATIONAL_SPLIT},
	{"IntegratorType","INT_RATIONAL_QUOTIENT",INT_RATIONAL_QUOTIENT},
	{NULL,NULL,0}
};

bool_t
vml_IntegratorLevel (VML *vmls, char *name,IntegratorLevel *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,IntegratorLevel_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map IntegratorLevel_map[] = {
	{"IntegratorLevel","EMBEDDED_INTEGRATOR",EMBEDDED_INTEGRATOR},
	{"IntegratorLevel","TOP_LEVEL_INTEGRATOR",TOP_LEVEL_INTEGRATOR},
	{NULL,NULL,0}
};

bool_t
vml_ReunitarizeType (VML *vmls, char *name,ReunitarizeType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,ReunitarizeType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map ReunitarizeType_map[] = {
	{"ReunitarizeType","REUNITARIZE_NO",REUNITARIZE_NO},
	{"ReunitarizeType","REUNITARIZE_YES",REUNITARIZE_YES},
	{NULL,NULL,0}
};

bool_t
vml_ReproduceTest (VML *vmls, char *name,ReproduceTest *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,ReproduceTest_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map ReproduceTest_map[] = {
	{"ReproduceTest","REPRODUCE_NO",REPRODUCE_NO},
	{"ReproduceTest","REPRODUCE_YES",REPRODUCE_YES},
	{NULL,NULL,0}
};

bool_t
vml_TestReproduceTest (VML *vmls, char *name,TestReproduceTest *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,TestReproduceTest_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map TestReproduceTest_map[] = {
	{"TestReproduceTest","TEST_REPRODUCE_NO",TEST_REPRODUCE_NO},
	{"TestReproduceTest","TEST_REPRODUCE_YES",TEST_REPRODUCE_YES},
	{NULL,NULL,0}
};

bool_t
vml_ReverseTest (VML *vmls, char *name,ReverseTest *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,ReverseTest_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map ReverseTest_map[] = {
	{"ReverseTest","REVERSE_NO",REVERSE_NO},
	{"ReverseTest","REVERSE_YES",REVERSE_YES},
	{NULL,NULL,0}
};

bool_t
vml_MetropolisType (VML *vmls, char *name,MetropolisType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,MetropolisType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map MetropolisType_map[] = {
	{"MetropolisType","METROPOLIS_NO",METROPOLIS_NO},
	{"MetropolisType","METROPOLIS_YES",METROPOLIS_YES},
	{NULL,NULL,0}
};

bool_t
vml_ForceMeasure (VML *vmls, char *name,ForceMeasure *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,ForceMeasure_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map ForceMeasure_map[] = {
	{"ForceMeasure","FORCE_MEASURE_NO",FORCE_MEASURE_NO},
	{"ForceMeasure","FORCE_MEASURE_YES",FORCE_MEASURE_YES},
	{NULL,NULL,0}
};

bool_t
vml_EigenMeasure (VML *vmls, char *name,EigenMeasure *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,EigenMeasure_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map EigenMeasure_map[] = {
	{"EigenMeasure","EIGEN_MEASURE_NO",EIGEN_MEASURE_NO},
	{"EigenMeasure","EIGEN_MEASURE_YES",EIGEN_MEASURE_YES},
	{NULL,NULL,0}
};

bool_t
vml_RhmcPolesAction (VML *vmls, char *name,RhmcPolesAction *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,RhmcPolesAction_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map RhmcPolesAction_map[] = {
	{"RhmcPolesAction","RHMC_POLES_CALC",RHMC_POLES_CALC},
	{"RhmcPolesAction","RHMC_POLES_READ",RHMC_POLES_READ},
	{"RhmcPolesAction","RHMC_POLES_CALC_WRITE",RHMC_POLES_CALC_WRITE},
	{NULL,NULL,0}
};

bool_t
vml_HmdLimits (VML *vmls, char *name,HmdLimits *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,HmdLimits_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map HmdLimits_map[] = {
	{"HmdLimits","MAX_HMD_MASSES",MAX_HMD_MASSES},
	{"HmdLimits","MAX_RAT_DEGREE",MAX_RAT_DEGREE},
	{NULL,NULL,0}
};

bool_t
vml_InverterType (VML *vmls, char *name,InverterType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,InverterType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map InverterType_map[] = {
	{"InverterType","CG",CG},
	{"InverterType","BICGSTAB",BICGSTAB},
	{"InverterType","EIGCG",EIGCG},
	{"InverterType","LOWMODEAPPROX",LOWMODEAPPROX},
	{"InverterType","CG_LOWMODE_DEFL",CG_LOWMODE_DEFL},
	{"InverterType","HDCG",HDCG},
	{NULL,NULL,0}
};

bool_t
vml_RationalApproxType (VML *vmls, char *name,RationalApproxType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,RationalApproxType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map RationalApproxType_map[] = {
	{"RationalApproxType","RATIONAL_APPROX_POWER",RATIONAL_APPROX_POWER},
	{"RationalApproxType","RATIONAL_APPROX_QUOTIENT",RATIONAL_APPROX_QUOTIENT},
	{"RationalApproxType","RATIONAL_APPROX_ZERO_POLE",RATIONAL_APPROX_ZERO_POLE},
	{NULL,NULL,0}
};

bool_t
vml_RationalBoundsType (VML *vmls, char *name,RationalBoundsType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,RationalBoundsType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map RationalBoundsType_map[] = {
	{"RationalBoundsType","RATIONAL_BOUNDS_AUTOMATIC",RATIONAL_BOUNDS_AUTOMATIC},
	{"RationalBoundsType","RATIONAL_BOUNDS_MANUAL",RATIONAL_BOUNDS_MANUAL},
	{NULL,NULL,0}
};

bool_t
vml_StaticBActionLinkSmearType (VML *vmls, char *name,StaticBActionLinkSmearType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,StaticBActionLinkSmearType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map StaticBActionLinkSmearType_map[] = {
	{"StaticBActionLinkSmearType","SB_ALS_NONE",SB_ALS_NONE},
	{"StaticBActionLinkSmearType","SB_ALS_APE",SB_ALS_APE},
	{"StaticBActionLinkSmearType","SB_ALS_APE_NO_PROJ",SB_ALS_APE_NO_PROJ},
	{"StaticBActionLinkSmearType","SB_ALS_APE_OLEG",SB_ALS_APE_OLEG},
	{"StaticBActionLinkSmearType","SB_ALS_HYP_HK",SB_ALS_HYP_HK},
	{"StaticBActionLinkSmearType","SB_ALS_HYP_L",SB_ALS_HYP_L},
	{"StaticBActionLinkSmearType","SB_ALS_HYP_2",SB_ALS_HYP_2},
	{"StaticBActionLinkSmearType","SB_ALS_STOUT",SB_ALS_STOUT},
	{NULL,NULL,0}
};

bool_t
vml_GaussianKernelLinkSmearType (VML *vmls, char *name,GaussianKernelLinkSmearType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,GaussianKernelLinkSmearType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map GaussianKernelLinkSmearType_map[] = {
	{"GaussianKernelLinkSmearType","GKLS_NONE",GKLS_NONE},
	{"GaussianKernelLinkSmearType","GKLS_APE",GKLS_APE},
	{"GaussianKernelLinkSmearType","GKLS_STOUT",GKLS_STOUT},
	{NULL,NULL,0}
};

bool_t
vml_CalcQpropType (VML *vmls, char *name,CalcQpropType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,CalcQpropType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map CalcQpropType_map[] = {
	{"CalcQpropType","READ_QPROP",READ_QPROP},
	{"CalcQpropType","NOIO_QPROP",NOIO_QPROP},
	{"CalcQpropType","WRITE_QPROP",WRITE_QPROP},
	{NULL,NULL,0}
};

bool_t
vml_CalcSeqType (VML *vmls, char *name,CalcSeqType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,CalcSeqType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map CalcSeqType_map[] = {
	{"CalcSeqType","READ_SEQ",READ_SEQ},
	{"CalcSeqType","NOIO_SEQ",NOIO_SEQ},
	{"CalcSeqType","WRITE_SEQ",WRITE_SEQ},
	{"CalcSeqType","MULT_SEQ",MULT_SEQ},
	{"CalcSeqType","READ_MULT_SEQ",READ_MULT_SEQ},
	{"CalcSeqType","WRITE_MULT_SEQ",WRITE_MULT_SEQ},
	{NULL,NULL,0}
};

bool_t
vml_BfmSolverType (VML *vmls, char *name,BfmSolverType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,BfmSolverType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map BfmSolverType_map[] = {
	{"BfmSolverType","BFM_DWF",BFM_DWF},
	{"BfmSolverType","BFM_DWFrb4d",BFM_DWFrb4d},
	{"BfmSolverType","BFM_WilsonFermion",BFM_WilsonFermion},
	{"BfmSolverType","BFM_WilsonTM",BFM_WilsonTM},
	{"BfmSolverType","BFM_WilsonNN",BFM_WilsonNN},
	{"BfmSolverType","BFM_HwPartFracZolo",BFM_HwPartFracZolo},
	{"BfmSolverType","BFM_HwContFracZolo",BFM_HwContFracZolo},
	{"BfmSolverType","BFM_HwPartFracTanh",BFM_HwPartFracTanh},
	{"BfmSolverType","BFM_HwContFracTanh",BFM_HwContFracTanh},
	{"BfmSolverType","BFM_HwCayleyZolo",BFM_HwCayleyZolo},
	{"BfmSolverType","BFM_HtCayleyZolo",BFM_HtCayleyZolo},
	{"BfmSolverType","BFM_HwCayleyTanh",BFM_HwCayleyTanh},
	{"BfmSolverType","BFM_HmCayleyTanh",BFM_HmCayleyTanh},
	{"BfmSolverType","BFM_HtCayleyTanh",BFM_HtCayleyTanh},
	{"BfmSolverType","BFM_DWFTransfer",BFM_DWFTransfer},
	{"BfmSolverType","BFM_DWFTransferInv",BFM_DWFTransferInv},
	{"BfmSolverType","BFM_HtContFracTanh",BFM_HtContFracTanh},
	{"BfmSolverType","BFM_HtContFracZolo",BFM_HtContFracZolo},
	{NULL,NULL,0}
};
CPS_END_NAMESPACE
