/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/fix_gauge_arg.h>
CPS_START_NAMESPACE
	 bool FixGaugeArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool FixGaugeArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool FixGaugeArg::Vml(VML *vmls,char *instance){
		 if(!vml_FixGaugeArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_FixGaugeArg (VML *vmls, char *name,FixGaugeArg *objp)
{
	 vml_class_begin(vmls,"FixGaugeArg",name);
	 if (!vml_FixGaugeType (vmls, "fix_gauge_kind", &objp->fix_gauge_kind))
		 return FALSE;
	 if (!vml_int (vmls, "hyperplane_start", &objp->hyperplane_start))
		 return FALSE;
	 if (!vml_int (vmls, "hyperplane_step", &objp->hyperplane_step))
		 return FALSE;
	 if (!vml_int (vmls, "hyperplane_num", &objp->hyperplane_num))
		 return FALSE;
	 if (!vml_Float (vmls, "stop_cond", &objp->stop_cond))
		 return FALSE;
	 if (!vml_int (vmls, "max_iter_num", &objp->max_iter_num))
		 return FALSE;
	 vml_class_end(vmls,"FixGaugeArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
