/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/hmc_arg.h>
CPS_START_NAMESPACE
	 bool HmcArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool HmcArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool HmcArg::Vml(VML *vmls,char *instance){
		 if(!vml_HmcArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_HmcArg (VML *vmls, char *name,HmcArg *objp)
{
	 vml_class_begin(vmls,"HmcArg",name);
	 if (!vml_int (vmls, "steps_per_traj", &objp->steps_per_traj))
		 return FALSE;
	 if (!vml_Float (vmls, "step_size", &objp->step_size))
		 return FALSE;
	 if (!vml_MetropolisType (vmls, "metropolis", &objp->metropolis))
		 return FALSE;
	 if (!vml_ReunitarizeType (vmls, "reunitarize", &objp->reunitarize))
		 return FALSE;
	 if (!vml_ReverseTest (vmls, "reverse", &objp->reverse))
		 return FALSE;
	 if (!vml_ReproduceTest (vmls, "reproduce", &objp->reproduce))
		 return FALSE;
	 if (!vml_int (vmls, "reproduce_attempt_limit", &objp->reproduce_attempt_limit))
		 return FALSE;
	 if (!vml_bool (vmls, "wfm_md_sloppy", &objp->wfm_md_sloppy))
		 return FALSE;
	 vml_class_end(vmls,"HmcArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
