/*
 * Please do not edit this file.
 * It was generated by CPC make system.
 */

#include "alg/hyp_smear_arg.h"
CPS_START_NAMESPACE
	 HypSmearArg::HypSmearArg (char *file) {
	   Decode(file,"instance");
	 };
	 void HypSmearArg::Encode(char *filename,char *instance){
		 VML vmls;
		 vmls.Create(filename,VML_ENCODE);
		 Vml(&vmls,instance);
		 vmls.Destroy();
	 }

	 void HypSmearArg::Decode(char *filename,char *instance){
		 VML vmls;
		 vmls.Create(filename,VML_DECODE);
		 Vml(&vmls,instance);
		 vmls.Destroy();
	 }
	 void HypSmearArg::Vml(VML *vmls,char *instance){
		 vml_HypSmearArg(vmls,instance,this);
	 }


bool_t
vml_HypSmearArg (VML *vmls, char *name,HypSmearArg *objp)
{
	register int32_t *buf;

	 vml_class_begin(vmls,"HypSmearArg",name);
	 if (!vml_Float (vmls, "tolerance", &objp->tolerance))
		 return VML_FALSE;
	 if (!vml_int (vmls, "orthog", &objp->orthog))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "c1", &objp->c1))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "c2", &objp->c2))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "c3", &objp->c3))
		 return VML_FALSE;
	 vml_class_end(vmls,"HypSmearArg",name);
	return VML_TRUE;
}
CPS_END_NAMESPACE
