/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/hyp_smear_arg.h>
CPS_START_NAMESPACE
	 bool HypSmearArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool HypSmearArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool HypSmearArg::Vml(VML *vmls,char *instance){
		 if(!vml_HypSmearArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_HypSmearArg (VML *vmls, char *name,HypSmearArg *objp)
{
	 vml_class_begin(vmls,"HypSmearArg",name);
	 if (!vml_Float (vmls, "tolerance", &objp->tolerance))
		 return FALSE;
	 if (!vml_int (vmls, "orthog", &objp->orthog))
		 return FALSE;
	 if (!vml_Float (vmls, "c1", &objp->c1))
		 return FALSE;
	 if (!vml_Float (vmls, "c2", &objp->c2))
		 return FALSE;
	 if (!vml_Float (vmls, "c3", &objp->c3))
		 return FALSE;
	 vml_class_end(vmls,"HypSmearArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
