/*
 * Please do not edit this file.
 * It was generated by CPC make system.
 */

#include "alg/kinetic_smear_arg.h"
CPS_START_NAMESPACE
	 KineticSmearArg::KineticSmearArg (char *file) {
	   Decode(file,"instance");
	 };
	 void KineticSmearArg::Encode(char *filename,char *instance){
		 VML vmls;
		 vmls.Create(filename,VML_ENCODE);
		 Vml(&vmls,instance);
		 vmls.Destroy();
	 }

	 void KineticSmearArg::Decode(char *filename,char *instance){
		 VML vmls;
		 vmls.Create(filename,VML_DECODE);
		 Vml(&vmls,instance);
		 vmls.Destroy();
	 }
	 void KineticSmearArg::Vml(VML *vmls,char *instance){
		 vml_KineticSmearArg(vmls,instance,this);
	 }


bool_t
vml_KineticSmearArg (VML *vmls, char *name,KineticSmearArg *objp)
{
	register int32_t *buf;

	 vml_class_begin(vmls,"KineticSmearArg",name);
	 if (!vml_int (vmls, "orthog", &objp->orthog))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "single_link", &objp->single_link))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "three_link", &objp->three_link))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "five_link", &objp->five_link))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "seven_link", &objp->seven_link))
		 return VML_FALSE;
	 if (!vml_Float (vmls, "lepage", &objp->lepage))
		 return VML_FALSE;
	 vml_class_end(vmls,"KineticSmearArg",name);
	return VML_TRUE;
}
CPS_END_NAMESPACE
