/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/ktopipi_jobparams.h>
CPS_START_NAMESPACE
	 bool JobParams::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool JobParams::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool JobParams::Vml(VML *vmls,char *instance){
		 if(!vml_JobParams(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_JobParams (VML *vmls, char *name,JobParams *objp)
{
	 vml_class_begin(vmls,"JobParams",name);
	 if (!vml_BfmSolverType (vmls, "solver", &objp->solver))
		 return FALSE;
	 if (!vml_double (vmls, "mobius_scale", &objp->mobius_scale))
		 return FALSE;
	 if (!vml_double (vmls, "pion_rad", &objp->pion_rad))
		 return FALSE;
	 if (!vml_double (vmls, "kaon_rad", &objp->kaon_rad))
		 return FALSE;
	 if (!vml_int (vmls, "pipi_separation", &objp->pipi_separation))
		 return FALSE;
	 if (!vml_int (vmls, "tstep_pipi", &objp->tstep_pipi))
		 return FALSE;
	 if (!vml_array (vmls, "k_pi_separation", (char **)&objp->k_pi_separation.k_pi_separation_val, (u_int *) &objp->k_pi_separation.k_pi_separation_len, ~0,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_int (vmls, "xyzstep_type1", &objp->xyzstep_type1))
		 return FALSE;
	 if (!vml_int (vmls, "tstep_type12", &objp->tstep_type12))
		 return FALSE;
	 vml_class_end(vmls,"JobParams",name);
	return TRUE;
}
void rpc_print<JobParams>::doit(JobParams const &what, const std::string &prefix){
	std::cout << prefix << "{\n";
	std::string spaces(prefix.size(),' ');
	rpc_print<BfmSolverType>::doit(what.solver,spaces+" solver = ");
	rpc_print<double>::doit(what.mobius_scale,spaces+" mobius_scale = ");
	rpc_print<double>::doit(what.pion_rad,spaces+" pion_rad = ");
	rpc_print<double>::doit(what.kaon_rad,spaces+" kaon_rad = ");
	rpc_print<int>::doit(what.pipi_separation,spaces+" pipi_separation = ");
	rpc_print<int>::doit(what.tstep_pipi,spaces+" tstep_pipi = ");
	rpc_print<int *>::doit(what.k_pi_separation.k_pi_separation_val,what.k_pi_separation.k_pi_separation_len,spaces+" k_pi_separation = ");
	rpc_print<int>::doit(what.xyzstep_type1,spaces+" xyzstep_type1 = ");
	rpc_print<int>::doit(what.tstep_type12,spaces+" tstep_type12 = ");
	std::cout << spaces << "}\n";
}
void JobParams::print(const std::string &prefix){
	rpc_print<JobParams>::doit(*this,prefix);
}
void rpc_deepcopy<JobParams>::doit(JobParams &into, JobParams const &from){
	  rpc_deepcopy<BfmSolverType>::doit(into.solver,from.solver);
	  rpc_deepcopy<double>::doit(into.mobius_scale,from.mobius_scale);
	  rpc_deepcopy<double>::doit(into.pion_rad,from.pion_rad);
	  rpc_deepcopy<double>::doit(into.kaon_rad,from.kaon_rad);
	  rpc_deepcopy<int>::doit(into.pipi_separation,from.pipi_separation);
	  rpc_deepcopy<int>::doit(into.tstep_pipi,from.tstep_pipi);
	  into.k_pi_separation.k_pi_separation_len = from.k_pi_separation.k_pi_separation_len;
	  rpc_deepcopy<int *>::doit(into.k_pi_separation.k_pi_separation_val,from.k_pi_separation.k_pi_separation_val,from.k_pi_separation.k_pi_separation_len);
	  rpc_deepcopy<int>::doit(into.xyzstep_type1,from.xyzstep_type1);
	  rpc_deepcopy<int>::doit(into.tstep_type12,from.tstep_type12);
}
void JobParams::deep_copy(JobParams const &rhs){
	rpc_deepcopy<JobParams>::doit(*this,rhs);
}
CPS_END_NAMESPACE
