/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/lanczos_arg.h>
CPS_START_NAMESPACE
	 bool MatrixPolynomialArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool MatrixPolynomialArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool MatrixPolynomialArg::Vml(VML *vmls,char *instance){
		 if(!vml_MatrixPolynomialArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_MatrixPolynomialArg (VML *vmls, char *name,MatrixPolynomialArg *objp)
{
	 vml_class_begin(vmls,"MatrixPolynomialArg",name);
	 if (!vml_int (vmls, "Npol", &objp->Npol))
		 return FALSE;
	 if (!vml_array (vmls, "params", (char **)&objp->params.params_val, (u_int *) &objp->params.params_len, ~0,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_Pointer (vmls, "tmp1", &objp->tmp1))
		 return FALSE;
	 if (!vml_Pointer (vmls, "tmp2", &objp->tmp2))
		 return FALSE;
	 vml_class_end(vmls,"MatrixPolynomialArg",name);
	return TRUE;
}
	 bool LanczosArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool LanczosArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool LanczosArg::Vml(VML *vmls,char *instance){
		 if(!vml_LanczosArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_LanczosArg (VML *vmls, char *name,LanczosArg *objp)
{
	 vml_class_begin(vmls,"LanczosArg",name);
	 if (!vml_RitzMatType (vmls, "RitzMat_lanczos", &objp->RitzMat_lanczos))
		 return FALSE;
	 if (!vml_RitzMatType (vmls, "RitzMat_convcheck", &objp->RitzMat_convcheck))
		 return FALSE;
	 if (!vml_Float (vmls, "mass", &objp->mass))
		 return FALSE;
	 if (!vml_int (vmls, "nk_lanczos_vectors", &objp->nk_lanczos_vectors))
		 return FALSE;
	 if (!vml_int (vmls, "np_lanczos_vectors", &objp->np_lanczos_vectors))
		 return FALSE;
	 if (!vml_Float (vmls, "eigen_shift", &objp->eigen_shift))
		 return FALSE;
	 if (!vml_Float (vmls, "stop_residual", &objp->stop_residual))
		 return FALSE;
	 if (!vml_int (vmls, "maxiters", &objp->maxiters))
		 return FALSE;
	 if (!vml_int (vmls, "save", &objp->save))
		 return FALSE;
	 if (!vml_int (vmls, "conv_check", &objp->conv_check))
		 return FALSE;
	 if (!vml_string (vmls, "results", &objp->results, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "file", &objp->file, ~0))
		 return FALSE;
	 if (!vml_MatrixPolynomialArg (vmls, "matpoly_arg", &objp->matpoly_arg))
		 return FALSE;
	 vml_class_end(vmls,"LanczosArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
