/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/lanc_arg.h>
CPS_START_NAMESPACE

bool_t
vml_EigenType (VML *vmls, char *name,EigenType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,EigenType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map EigenType_map[] = {
	{"EigenType","D",D},
	{"EigenType","DDAG",DDAG},
	{"EigenType","G5D",G5D},
	{"EigenType","DDAGD",DDAGD},
	{NULL,NULL,0}
};
	 bool LancArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool LancArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool LancArg::Vml(VML *vmls,char *instance){
		 if(!vml_LancArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_LancArg (VML *vmls, char *name,LancArg *objp)
{
	 vml_class_begin(vmls,"LancArg",name);
	 if (!vml_Float (vmls, "mass", &objp->mass))
		 return FALSE;
	 if (!vml_Float (vmls, "stop_rsd", &objp->stop_rsd))
		 return FALSE;
	 if (!vml_Float (vmls, "qr_rsd", &objp->qr_rsd))
		 return FALSE;
	 if (!vml_EigenType (vmls, "EigenOper", &objp->EigenOper))
		 return FALSE;
	 if (!vml_bool (vmls, "precon", &objp->precon))
		 return FALSE;
	 if (!vml_int (vmls, "N_get", &objp->N_get))
		 return FALSE;
	 if (!vml_int (vmls, "N_use", &objp->N_use))
		 return FALSE;
	 if (!vml_int (vmls, "N_true_get", &objp->N_true_get))
		 return FALSE;
	 if (!vml_int (vmls, "ch_ord", &objp->ch_ord))
		 return FALSE;
	 if (!vml_Float (vmls, "ch_alpha", &objp->ch_alpha))
		 return FALSE;
	 if (!vml_Float (vmls, "ch_beta", &objp->ch_beta))
		 return FALSE;
	 if (!vml_bool (vmls, "ch_sh", &objp->ch_sh))
		 return FALSE;
	 if (!vml_Float (vmls, "ch_mu", &objp->ch_mu))
		 return FALSE;
	 if (!vml_bool (vmls, "lock", &objp->lock))
		 return FALSE;
	 if (!vml_int (vmls, "maxits", &objp->maxits))
		 return FALSE;
	 if (!vml_string (vmls, "fname", &objp->fname, ~0))
		 return FALSE;
	 vml_class_end(vmls,"LancArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
