/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/loc_arg.h>
CPS_START_NAMESPACE
	 bool LocArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool LocArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool LocArg::Vml(VML *vmls,char *instance){
		 if(!vml_LocArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_LocArg (VML *vmls, char *name,LocArg *objp)
{
	 vml_class_begin(vmls,"LocArg",name);
	 if (!vml_PatternType (vmls, "pattern_kind", &objp->pattern_kind))
		 return FALSE;
	 if (!vml_int (vmls, "n_loc", &objp->n_loc))
		 return FALSE;
	 if (!vml_int (vmls, "start", &objp->start))
		 return FALSE;
	 if (!vml_int (vmls, "step", &objp->step))
		 return FALSE;
	 if (!vml_array (vmls, "locs", (char **)&objp->locs.locs_val, (u_int *) &objp->locs.locs_len, ~0,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_int (vmls, "max_src", &objp->max_src))
		 return FALSE;
	 vml_class_end(vmls,"LocArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
