/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/matrixpolynomial_arg.h>
CPS_START_NAMESPACE
	 bool MatrixPolynomialArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool MatrixPolynomialArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool MatrixPolynomialArg::Vml(VML *vmls,char *instance){
		 if(!vml_MatrixPolynomialArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_MatrixPolynomialArg (VML *vmls, char *name,MatrixPolynomialArg *objp)
{
	 vml_class_begin(vmls,"MatrixPolynomialArg",name);
	int i;
	 if (!vml_int (vmls, "Npol", &objp->Npol))
		 return FALSE;
	 if (!vml_vector (vmls, "params", (char *)objp->params, 100,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_pointer (vmls, "tmp1", (char **)&objp->tmp1, sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_pointer (vmls, "tmp2", (char **)&objp->tmp2, sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 vml_class_end(vmls,"MatrixPolynomialArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
