/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/mom_arg.h>
CPS_START_NAMESPACE
	 bool MomArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool MomArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool MomArg::Vml(VML *vmls,char *instance){
		 if(!vml_MomArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_MomArg (VML *vmls, char *name,MomArg *objp)
{
	 vml_class_begin(vmls,"MomArg",name);
	int i;
	 if (!vml_int (vmls, "no_of_momenta", &objp->no_of_momenta))
		 return FALSE;
	 if (!vml_int (vmls, "deg", &objp->deg))
		 return FALSE;
	 if (!vml_int (vmls, "dir", &objp->dir))
		 return FALSE;
	 if (!vml_vector (vmls, "src_begin", (char *)objp->src_begin, 4,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_vector (vmls, "src_end", (char *)objp->src_end, 4,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 vml_class_end(vmls,"MomArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
