/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/muon_arg.h>
CPS_START_NAMESPACE

bool_t
vml_VP_TYPE (VML *vmls, char *name,VP_TYPE *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,VP_TYPE_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map VP_TYPE_map[] = {
	{"VP_TYPE","CONSERVED_LOCAL",CONSERVED_LOCAL},
	{"VP_TYPE","CONSERVED_LOCAL_LOWMODE",CONSERVED_LOCAL_LOWMODE},
	{"VP_TYPE","CONSERVED_LOCAL_PTSRC_TEST",CONSERVED_LOCAL_PTSRC_TEST},
	{"VP_TYPE","CONSERVED_LOCAL_LOOP_PTSRC",CONSERVED_LOCAL_LOOP_PTSRC},
	{"VP_TYPE","CONSERVED_LOCAL_TWISTED",CONSERVED_LOCAL_TWISTED},
	{NULL,NULL,0}
};
	 bool MuonArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool MuonArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool MuonArg::Vml(VML *vmls,char *instance){
		 if(!vml_MuonArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_MuonArg (VML *vmls, char *name,MuonArg *objp)
{
	 vml_class_begin(vmls,"MuonArg",name);
	int i;
	 if (!vml_u_long (vmls, "u1lat", &objp->u1lat))
		 return FALSE;
	 if (!vml_int (vmls, "source_time", &objp->source_time))
		 return FALSE;
	 if (!vml_int (vmls, "oper_time_start", &objp->oper_time_start))
		 return FALSE;
	 if (!vml_int (vmls, "oper_time_end", &objp->oper_time_end))
		 return FALSE;
	 if (!vml_int (vmls, "operator_gamma", &objp->operator_gamma))
		 return FALSE;
	 if (!vml_vector (vmls, "x", (char *)objp->x, 3,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_int (vmls, "n_source", &objp->n_source))
		 return FALSE;
	 if (!vml_int (vmls, "source_inc", &objp->source_inc))
		 return FALSE;
	 if (!vml_Float (vmls, "loop_mass", &objp->loop_mass))
		 return FALSE;
	 if (!vml_Float (vmls, "line_mass", &objp->line_mass))
		 return FALSE;
	 if (!vml_Float (vmls, "charge", &objp->charge))
		 return FALSE;
	 if (!vml_int (vmls, "GaugeFix", &objp->GaugeFix))
		 return FALSE;
	 if (!vml_int (vmls, "NPROJ", &objp->NPROJ))
		 return FALSE;
	 if (!vml_Float (vmls, "EPS", &objp->EPS))
		 return FALSE;
	 if (!vml_int (vmls, "XMOM", &objp->XMOM))
		 return FALSE;
	 if (!vml_int (vmls, "YMOM", &objp->YMOM))
		 return FALSE;
	 if (!vml_int (vmls, "ZMOM", &objp->ZMOM))
		 return FALSE;
	 if (!vml_int (vmls, "Nmom", &objp->Nmom))
		 return FALSE;
	 if (!vml_int (vmls, "MaxMomSq", &objp->MaxMomSq))
		 return FALSE;
	 if (!vml_int (vmls, "NConfs", &objp->NConfs))
		 return FALSE;
	 if (!vml_int (vmls, "NHITS", &objp->NHITS))
		 return FALSE;
	 if (!vml_string (vmls, "DIRVP", &objp->DIRVP, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "DIRML", &objp->DIRML, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "VPTAG", &objp->VPTAG, ~0))
		 return FALSE;
	 if (!vml_int (vmls, "DO_MUONLINE", &objp->DO_MUONLINE))
		 return FALSE;
	 if (!vml_int (vmls, "DO_VACPOL", &objp->DO_VACPOL))
		 return FALSE;
	 if (!vml_int (vmls, "tINC", &objp->tINC))
		 return FALSE;
	 if (!vml_int (vmls, "ptStart", &objp->ptStart))
		 return FALSE;
	 if (!vml_int (vmls, "ptINC", &objp->ptINC))
		 return FALSE;
	 if (!vml_int (vmls, "conf", &objp->conf))
		 return FALSE;
	 if (!vml_VP_TYPE (vmls, "vp_kind", &objp->vp_kind))
		 return FALSE;
	 if (!vml_string (vmls, "EIGTAG", &objp->EIGTAG, ~0))
		 return FALSE;
	 vml_class_end(vmls,"MuonArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
