/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/noise_arg.h>
CPS_START_NAMESPACE

bool_t
vml_NoiseType (VML *vmls, char *name,NoiseType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,NoiseType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map NoiseType_map[] = {
	{"NoiseType","GAUSSIAN",GAUSSIAN},
	{"NoiseType","FLAT",FLAT},
	{NULL,NULL,0}
};
	 bool NoiseArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool NoiseArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool NoiseArg::Vml(VML *vmls,char *instance){
		 if(!vml_NoiseArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_NoiseArg (VML *vmls, char *name,NoiseArg *objp)
{
	 vml_class_begin(vmls,"NoiseArg",name);
	 if (!vml_NoiseType (vmls, "noise_kind", &objp->noise_kind))
		 return FALSE;
	 if (!vml_Float (vmls, "size", &objp->size))
		 return FALSE;
	 vml_class_end(vmls,"NoiseArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
