/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/nuc3pt_arg.h>
CPS_START_NAMESPACE
	 bool Nuc3ptArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool Nuc3ptArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool Nuc3ptArg::Vml(VML *vmls,char *instance){
		 if(!vml_Nuc3ptArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_Nuc3ptArg (VML *vmls, char *name,Nuc3ptArg *objp)
{
	 vml_class_begin(vmls,"Nuc3ptArg",name);
	int i;
	 if (!vml_string (vmls, "cname", &objp->cname, ~0))
		 return FALSE;
	 if (!vml_int (vmls, "num_masses", &objp->num_masses))
		 return FALSE;
	 if (!vml_vector (vmls, "mass", (char *)objp->mass, 10,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_CgArg (vmls, "cg", &objp->cg))
		 return FALSE;
	 if (!vml_int (vmls, "t_source", &objp->t_source))
		 return FALSE;
	 if (!vml_int (vmls, "num_src", &objp->num_src))
		 return FALSE;
	 if (!vml_int (vmls, "source_inc", &objp->source_inc))
		 return FALSE;
	 if (!vml_int (vmls, "t_sink", &objp->t_sink))
		 return FALSE;
	 if (!vml_int (vmls, "BoxStart", &objp->BoxStart))
		 return FALSE;
	 if (!vml_int (vmls, "BoxEnd", &objp->BoxEnd))
		 return FALSE;
	 if (!vml_int (vmls, "gauss_N", &objp->gauss_N))
		 return FALSE;
	 if (!vml_Float (vmls, "gauss_W", &objp->gauss_W))
		 return FALSE;
	 if (!vml_vector (vmls, "x", (char *)objp->x, 3,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_Float (vmls, "theta", &objp->theta))
		 return FALSE;
	 if (!vml_int (vmls, "load_u1_lat", &objp->load_u1_lat))
		 return FALSE;
	 if (!vml_pointer (vmls, "u1_gauge_ptr", (char **)&objp->u1_gauge_ptr, sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_SourceType (vmls, "src_type", &objp->src_type))
		 return FALSE;
	 if (!vml_int (vmls, "DoUnPolarized", &objp->DoUnPolarized))
		 return FALSE;
	 if (!vml_int (vmls, "DoUnPolarizedMom", &objp->DoUnPolarizedMom))
		 return FALSE;
	 if (!vml_int (vmls, "DoPolarized", &objp->DoPolarized))
		 return FALSE;
	 if (!vml_int (vmls, "DoPolarizedMom", &objp->DoPolarizedMom))
		 return FALSE;
	 if (!vml_int (vmls, "DoHalfFermion", &objp->DoHalfFermion))
		 return FALSE;
	 if (!vml_int (vmls, "DoPerPlusAper", &objp->DoPerPlusAper))
		 return FALSE;
	 if (!vml_int (vmls, "MaxMom2", &objp->MaxMom2))
		 return FALSE;
	 if (!vml_int (vmls, "DoSS2ptF", &objp->DoSS2ptF))
		 return FALSE;
	 if (!vml_int (vmls, "DoGa1Proj", &objp->DoGa1Proj))
		 return FALSE;
	 if (!vml_int (vmls, "DoConserved", &objp->DoConserved))
		 return FALSE;
	 if (!vml_int (vmls, "num_mult", &objp->num_mult))
		 return FALSE;
	 if (!vml_vector (vmls, "mt", (char *)objp->mt, 5,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_GaussianKernelLinkSmearType (vmls, "gauss_link_smear_type", &objp->gauss_link_smear_type))
		 return FALSE;
	 if (!vml_int (vmls, "gauss_link_smear_N", &objp->gauss_link_smear_N))
		 return FALSE;
	 if (!vml_Float (vmls, "gauss_link_smear_coeff", &objp->gauss_link_smear_coeff))
		 return FALSE;
	 if (!vml_CalcQpropType (vmls, "calc_QProp", &objp->calc_QProp))
		 return FALSE;
	 if (!vml_CalcSeqType (vmls, "calc_seqQ", &objp->calc_seqQ))
		 return FALSE;
	 if (!vml_string (vmls, "prop_file", &objp->prop_file, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "ensemble_label", &objp->ensemble_label, ~0))
		 return FALSE;
	 if (!vml_int (vmls, "ensemble_id", &objp->ensemble_id))
		 return FALSE;
	 vml_class_end(vmls,"Nuc3ptArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
