/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/pbp_arg.h>
CPS_START_NAMESPACE

bool_t
vml_PBP_LIM (VML *vmls, char *name,PBP_LIM *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,PBP_LIM_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map PBP_LIM_map[] = {
	{"PBP_LIM","MAX_PBP_MASSES",MAX_PBP_MASSES},
	{NULL,NULL,0}
};
	 bool PbpArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool PbpArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool PbpArg::Vml(VML *vmls,char *instance){
		 if(!vml_PbpArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_PbpArg (VML *vmls, char *name,PbpArg *objp)
{
	 vml_class_begin(vmls,"PbpArg",name);
	int i;
	 if (!vml_PatternType (vmls, "pattern_kind", &objp->pattern_kind))
		 return FALSE;
	 if (!vml_int (vmls, "n_masses", &objp->n_masses))
		 return FALSE;
	 if (!vml_Float (vmls, "mass_start", &objp->mass_start))
		 return FALSE;
	 if (!vml_Float (vmls, "mass_step", &objp->mass_step))
		 return FALSE;
	 if (!vml_vector (vmls, "mass", (char *)objp->mass, MAX_PBP_MASSES,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_int (vmls, "max_num_iter", &objp->max_num_iter))
		 return FALSE;
	 if (!vml_Float (vmls, "stop_rsd", &objp->stop_rsd))
		 return FALSE;
	 if (!vml_int (vmls, "src_u_s", &objp->src_u_s))
		 return FALSE;
	 if (!vml_int (vmls, "src_l_s", &objp->src_l_s))
		 return FALSE;
	 if (!vml_int (vmls, "snk_u_s", &objp->snk_u_s))
		 return FALSE;
	 if (!vml_int (vmls, "snk_l_s", &objp->snk_l_s))
		 return FALSE;
	 if (!vml_int (vmls, "snk_loop", &objp->snk_loop))
		 return FALSE;
	 vml_class_end(vmls,"PbpArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
