/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/pot_arg.h>
CPS_START_NAMESPACE
	 bool PotArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool PotArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool PotArg::Vml(VML *vmls,char *instance){
		 if(!vml_PotArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_PotArg (VML *vmls, char *name,PotArg *objp)
{
	 vml_class_begin(vmls,"PotArg",name);
	 if (!vml_int (vmls, "prop_dir", &objp->prop_dir))
		 return FALSE;
	 if (!vml_int (vmls, "therm_steps", &objp->therm_steps))
		 return FALSE;
	 if (!vml_int (vmls, "therm_meas", &objp->therm_meas))
		 return FALSE;
	 if (!vml_int (vmls, "xi", &objp->xi))
		 return FALSE;
	 if (!vml_int (vmls, "check", &objp->check))
		 return FALSE;
	 if (!vml_int (vmls, "sweep", &objp->sweep))
		 return FALSE;
	 if (!vml_int (vmls, "max_X", &objp->max_X))
		 return FALSE;
	 if (!vml_int (vmls, "max_Y", &objp->max_Y))
		 return FALSE;
	 if (!vml_int (vmls, "max_Z", &objp->max_Z))
		 return FALSE;
	 if (!vml_int (vmls, "max_T", &objp->max_T))
		 return FALSE;
	 vml_class_end(vmls,"PotArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
