/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/remez_arg.h>
CPS_START_NAMESPACE
	 bool RemezArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool RemezArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool RemezArg::Vml(VML *vmls,char *instance){
		 if(!vml_RemezArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_RemezArg (VML *vmls, char *name,RemezArg *objp)
{
	 vml_class_begin(vmls,"RemezArg",name);
	int i;
	 if (!vml_RationalApproxType (vmls, "approx_type", &objp->approx_type))
		 return FALSE;
	 if (!vml_int (vmls, "valid_approx", &objp->valid_approx))
		 return FALSE;
	 if (!vml_int (vmls, "degree", &objp->degree))
		 return FALSE;
	 if (!vml_Float (vmls, "lambda_low", &objp->lambda_low))
		 return FALSE;
	 if (!vml_Float (vmls, "lambda_high", &objp->lambda_high))
		 return FALSE;
	 if (!vml_int (vmls, "power_num", &objp->power_num))
		 return FALSE;
	 if (!vml_int (vmls, "power_den", &objp->power_den))
		 return FALSE;
	 if (!vml_FieldType (vmls, "field_type", &objp->field_type))
		 return FALSE;
	 if (!vml_Float (vmls, "error", &objp->error))
		 return FALSE;
	 if (!vml_Float (vmls, "norm", &objp->norm))
		 return FALSE;
	 if (!vml_vector (vmls, "residue", (char *)objp->residue, MAX_RAT_DEGREE,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_vector (vmls, "pole", (char *)objp->pole, MAX_RAT_DEGREE,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_Float (vmls, "norm_inv", &objp->norm_inv))
		 return FALSE;
	 if (!vml_vector (vmls, "residue_inv", (char *)objp->residue_inv, MAX_RAT_DEGREE,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_vector (vmls, "pole_inv", (char *)objp->pole_inv, MAX_RAT_DEGREE,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_long (vmls, "precision", &objp->precision))
		 return FALSE;
	 if (!vml_Float (vmls, "delta_m", &objp->delta_m))
		 return FALSE;
	 vml_class_end(vmls,"RemezArg",name);
	return TRUE;
}
	 bool RationalQuotientRemezArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool RationalQuotientRemezArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool RationalQuotientRemezArg::Vml(VML *vmls,char *instance){
		 if(!vml_RationalQuotientRemezArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_RationalQuotientRemezArg (VML *vmls, char *name,RationalQuotientRemezArg *objp)
{
	 vml_class_begin(vmls,"RationalQuotientRemezArg",name);
	 if (!vml_array (vmls, "bsn_md", (char **)&objp->bsn_md.bsn_md_val, (u_int *) &objp->bsn_md.bsn_md_len, ~0,
		sizeof (RemezArg), (vmlproc_t) vml_RemezArg))
		 return FALSE;
	 if (!vml_array (vmls, "bsn_mc", (char **)&objp->bsn_mc.bsn_mc_val, (u_int *) &objp->bsn_mc.bsn_mc_len, ~0,
		sizeof (RemezArg), (vmlproc_t) vml_RemezArg))
		 return FALSE;
	 if (!vml_array (vmls, "frm_md", (char **)&objp->frm_md.frm_md_val, (u_int *) &objp->frm_md.frm_md_len, ~0,
		sizeof (RemezArg), (vmlproc_t) vml_RemezArg))
		 return FALSE;
	 if (!vml_array (vmls, "frm_mc", (char **)&objp->frm_mc.frm_mc_val, (u_int *) &objp->frm_mc.frm_mc_len, ~0,
		sizeof (RemezArg), (vmlproc_t) vml_RemezArg))
		 return FALSE;
	 vml_class_end(vmls,"RationalQuotientRemezArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
