/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/s_spect_arg.h>
CPS_START_NAMESPACE

bool_t
vml_StagQuarkSrcType (VML *vmls, char *name,StagQuarkSrcType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,StagQuarkSrcType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map StagQuarkSrcType_map[] = {
	{"StagQuarkSrcType","S_QUARK_POINT",S_QUARK_POINT},
	{"StagQuarkSrcType","WALLZ",WALLZ},
	{"StagQuarkSrcType","WALL2Z",WALL2Z},
	{NULL,NULL,0}
};

bool_t
vml_StagQuarkLocalType (VML *vmls, char *name,StagQuarkLocalType *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,StagQuarkLocalType_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map StagQuarkLocalType_map[] = {
	{"StagQuarkLocalType","LOCAL",LOCAL},
	{"StagQuarkLocalType","NONLOCAL",NONLOCAL},
	{NULL,NULL,0}
};

bool_t
vml_StagQuarkDir (VML *vmls, char *name,StagQuarkDir *objp)
{
	if (!vml_enum (vmls,name,(enum_t *)objp,StagQuarkDir_map))
		return FALSE;
	return TRUE;
}
struct vml_enum_map StagQuarkDir_map[] = {
	{"StagQuarkDir","HDM_X",HDM_X},
	{"StagQuarkDir","HDM_Y",HDM_Y},
	{"StagQuarkDir","HDM_Z",HDM_Z},
	{"StagQuarkDir","HDM_T",HDM_T},
	{NULL,NULL,0}
};
	 bool StagQuarkSrc::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool StagQuarkSrc::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool StagQuarkSrc::Vml(VML *vmls,char *instance){
		 if(!vml_StagQuarkSrc(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_StagQuarkSrc (VML *vmls, char *name,StagQuarkSrc *objp)
{
	 vml_class_begin(vmls,"StagQuarkSrc",name);
	int i;
	 if (!vml_StagQuarkSrcType (vmls, "type", &objp->type))
		 return FALSE;
	 if (!vml_vector (vmls, "origin", (char *)objp->origin, 4,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_vector (vmls, "end", (char *)objp->end, 4,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_StagQuarkDir (vmls, "dir", &objp->dir))
		 return FALSE;
	 vml_class_end(vmls,"StagQuarkSrc",name);
	return TRUE;
}
	 bool StagQuarkArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool StagQuarkArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool StagQuarkArg::Vml(VML *vmls,char *instance){
		 if(!vml_StagQuarkArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_StagQuarkArg (VML *vmls, char *name,StagQuarkArg *objp)
{
	 vml_class_begin(vmls,"StagQuarkArg",name);
	 if (!vml_int (vmls, "qid", &objp->qid))
		 return FALSE;
	 if (!vml_CgArg (vmls, "cg", &objp->cg))
		 return FALSE;
	 if (!vml_StagQuarkSrc (vmls, "src", &objp->src))
		 return FALSE;
	 if (!vml_StagQuarkLocalType (vmls, "sln", &objp->sln))
		 return FALSE;
	 vml_class_end(vmls,"StagQuarkArg",name);
	return TRUE;
}
	 bool StagMesonArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool StagMesonArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool StagMesonArg::Vml(VML *vmls,char *instance){
		 if(!vml_StagMesonArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_StagMesonArg (VML *vmls, char *name,StagMesonArg *objp)
{
	 vml_class_begin(vmls,"StagMesonArg",name);
	 if (!vml_int (vmls, "qid0", &objp->qid0))
		 return FALSE;
	 if (!vml_int (vmls, "qid1", &objp->qid1))
		 return FALSE;
	 if (!vml_StagQuarkDir (vmls, "dir", &objp->dir))
		 return FALSE;
	 if (!vml_u_long (vmls, "meson_buf", &objp->meson_buf))
		 return FALSE;
	 vml_class_end(vmls,"StagMesonArg",name);
	return TRUE;
}
	 bool StagMomMesonArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool StagMomMesonArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool StagMomMesonArg::Vml(VML *vmls,char *instance){
		 if(!vml_StagMomMesonArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_StagMomMesonArg (VML *vmls, char *name,StagMomMesonArg *objp)
{
	 vml_class_begin(vmls,"StagMomMesonArg",name);
	 if (!vml_int (vmls, "qid0", &objp->qid0))
		 return FALSE;
	 if (!vml_int (vmls, "qid1", &objp->qid1))
		 return FALSE;
	 if (!vml_StagQuarkDir (vmls, "dir", &objp->dir))
		 return FALSE;
	 if (!vml_int (vmls, "no_of_momenta", &objp->no_of_momenta))
		 return FALSE;
	 if (!vml_u_long (vmls, "meson_buf", &objp->meson_buf))
		 return FALSE;
	 vml_class_end(vmls,"StagMomMesonArg",name);
	return TRUE;
}
	 bool StagNucleonArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool StagNucleonArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool StagNucleonArg::Vml(VML *vmls,char *instance){
		 if(!vml_StagNucleonArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_StagNucleonArg (VML *vmls, char *name,StagNucleonArg *objp)
{
	 vml_class_begin(vmls,"StagNucleonArg",name);
	 if (!vml_int (vmls, "qid0", &objp->qid0))
		 return FALSE;
	 if (!vml_int (vmls, "qid1", &objp->qid1))
		 return FALSE;
	 if (!vml_int (vmls, "qid2", &objp->qid2))
		 return FALSE;
	 if (!vml_StagQuarkDir (vmls, "dir", &objp->dir))
		 return FALSE;
	 if (!vml_u_long (vmls, "nucleon_buf", &objp->nucleon_buf))
		 return FALSE;
	 vml_class_end(vmls,"StagNucleonArg",name);
	return TRUE;
}
	 bool StagNonLocalArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool StagNonLocalArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool StagNonLocalArg::Vml(VML *vmls,char *instance){
		 if(!vml_StagNonLocalArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_StagNonLocalArg (VML *vmls, char *name,StagNonLocalArg *objp)
{
	 vml_class_begin(vmls,"StagNonLocalArg",name);
	 if (!vml_int (vmls, "qid0", &objp->qid0))
		 return FALSE;
	 if (!vml_int (vmls, "qid1", &objp->qid1))
		 return FALSE;
	 if (!vml_int (vmls, "qid2", &objp->qid2))
		 return FALSE;
	 if (!vml_StagQuarkDir (vmls, "dir", &objp->dir))
		 return FALSE;
	 if (!vml_u_long (vmls, "nlocal_buf", &objp->nlocal_buf))
		 return FALSE;
	 vml_class_end(vmls,"StagNonLocalArg",name);
	return TRUE;
}
	 bool NLStagMesonArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool NLStagMesonArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool NLStagMesonArg::Vml(VML *vmls,char *instance){
		 if(!vml_NLStagMesonArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_NLStagMesonArg (VML *vmls, char *name,NLStagMesonArg *objp)
{
	 vml_class_begin(vmls,"NLStagMesonArg",name);
	int i;
	 if (!vml_vector (vmls, "qid0", (char *)objp->qid0, 8,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_StagQuarkDir (vmls, "dir", &objp->dir))
		 return FALSE;
	 if (!vml_u_long (vmls, "nlocal_buf", &objp->nlocal_buf))
		 return FALSE;
	 vml_class_end(vmls,"NLStagMesonArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
