/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/w_spect_arg.h>
CPS_START_NAMESPACE
	 bool WspectOutput::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool WspectOutput::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool WspectOutput::Vml(VML *vmls,char *instance){
		 if(!vml_WspectOutput(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_WspectOutput (VML *vmls, char *name,WspectOutput *objp)
{
	register int32_t *buf;

	 vml_class_begin(vmls,"WspectOutput",name);
	 if (!vml_WbaryonFold (vmls, "fold", &objp->fold))
		 return FALSE;
	 if (!vml_string (vmls, "cg", &objp->cg, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "cg2", &objp->cg2, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "pbp", &objp->pbp, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "mid_point", &objp->mid_point, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "a0_p", &objp->a0_p, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "a1", &objp->a1, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "b1", &objp->b1, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "pion", &objp->pion, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "pion_prime", &objp->pion_prime, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho", &objp->rho, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho_prime", &objp->rho_prime, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "a0", &objp->a0, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "a0_prime", &objp->a0_prime, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "a1_x", &objp->a1_x, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "a1_y", &objp->a1_y, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "a1_z", &objp->a1_z, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "b1_x", &objp->b1_x, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "b1_y", &objp->b1_y, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "b1_z", &objp->b1_z, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho_x", &objp->rho_x, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho_y", &objp->rho_y, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho_z", &objp->rho_z, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho_x_prime", &objp->rho_x_prime, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho_y_prime", &objp->rho_y_prime, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "rho_z_prime", &objp->rho_z_prime, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "nucleon", &objp->nucleon, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "nucleon_prime", &objp->nucleon_prime, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "delta_x", &objp->delta_x, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "delta_y", &objp->delta_y, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "delta_z", &objp->delta_z, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "delta_t", &objp->delta_t, ~0))
		 return FALSE;
	 vml_class_end(vmls,"WspectOutput",name);
	return TRUE;
}
	 bool WspectArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool WspectArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool WspectArg::Vml(VML *vmls,char *instance){
		 if(!vml_WspectArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_WspectArg (VML *vmls, char *name,WspectArg *objp)
{
	register int32_t *buf;

	 vml_class_begin(vmls,"WspectArg",name);
	int i;
	 if (!vml_string (vmls, "CgArgFile", &objp->CgArgFile, ~0))
		 return FALSE;
	 if (!vml_string (vmls, "WspectOutputFile", &objp->WspectOutputFile, ~0))
		 return FALSE;
	 if (!vml_int (vmls, "prop_dir", &objp->prop_dir))
		 return FALSE;
	 if (!vml_int (vmls, "num_mom", &objp->num_mom))
		 return FALSE;
	 if (!vml_SourceKind (vmls, "source_kind", &objp->source_kind))
		 return FALSE;
	 if (!vml_vector (vmls, "src_box_b", (char *)objp->src_box_b, 4,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_vector (vmls, "src_box_e", (char *)objp->src_box_e, 4,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_Float (vmls, "g_epsi", &objp->g_epsi))
		 return FALSE;
	 if (!vml_int (vmls, "g_n", &objp->g_n))
		 return FALSE;
	 if (!vml_vector (vmls, "g_center", (char *)objp->g_center, 4,
		sizeof (int), (vmlproc_t) vml_int))
		 return FALSE;
	 if (!vml_Float (vmls, "rescale_factor", &objp->rescale_factor))
		 return FALSE;
	 if (!vml_int (vmls, "aots_num", &objp->aots_num))
		 return FALSE;
	 if (!vml_int (vmls, "aots_start", &objp->aots_start))
		 return FALSE;
	 if (!vml_int (vmls, "aots_step", &objp->aots_step))
		 return FALSE;
	 if (!vml_int (vmls, "baryons_on", &objp->baryons_on))
		 return FALSE;
	 if (!vml_int (vmls, "normal_mesons_on", &objp->normal_mesons_on))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesons_on", &objp->extended_mesons_on))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesonsBE_on", &objp->extended_mesonsBE_on))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesons_op_groupId", &objp->extended_mesons_op_groupId))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesons_first_dev_on", &objp->extended_mesons_first_dev_on))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesons_second_sym_dev_on", &objp->extended_mesons_second_sym_dev_on))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesons_second_antisym_dev_on", &objp->extended_mesons_second_antisym_dev_on))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesons_second_diag_dev_on", &objp->extended_mesons_second_diag_dev_on))
		 return FALSE;
	 if (!vml_int (vmls, "fuzzing_on", &objp->fuzzing_on))
		 return FALSE;
	 if (!vml_int (vmls, "sink_fuzzing_only", &objp->sink_fuzzing_only))
		 return FALSE;
	 if (!vml_int (vmls, "fuzzing_level", &objp->fuzzing_level))
		 return FALSE;
	 if (!vml_int (vmls, "fuzzing_c_num", &objp->fuzzing_c_num))
		 return FALSE;
	 if (!vml_vector (vmls, "fuzzing_c", (char *)objp->fuzzing_c, MAX_FUZZING_C_NUM,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_int (vmls, "fuzzing_hits", &objp->fuzzing_hits))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesonsBE_op_groupId", &objp->extended_mesonsBE_op_groupId))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesonsBE_Elec_on", &objp->extended_mesonsBE_Elec_on))
		 return FALSE;
	 if (!vml_int (vmls, "extended_mesonsBE_Magn_on", &objp->extended_mesonsBE_Magn_on))
		 return FALSE;
	 if (!vml_int (vmls, "BEfuzzing_on", &objp->BEfuzzing_on))
		 return FALSE;
	 if (!vml_int (vmls, "BEfuzzing_level", &objp->BEfuzzing_level))
		 return FALSE;
	 if (!vml_int (vmls, "BEfuzzing_c_num", &objp->BEfuzzing_c_num))
		 return FALSE;
	 if (!vml_vector (vmls, "BEfuzzing_c", (char *)objp->BEfuzzing_c, MAX_FUZZING_C_NUM,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_int (vmls, "BEfuzzing_hits", &objp->BEfuzzing_hits))
		 return FALSE;
	 vml_class_end(vmls,"WspectArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
