#SEPARATE_LIB=yes
NORECURSE_DIR = CVS  bgl noarch qcdoc qcdsp qcdsp_lcl_nos qcdsp_nos qcdsp_nos_hdw_diag qcdsp_scl noarch_pv bgp bgp_asm bg_bagel bg_bagel_spi bgl bgq qmp noarch_bagel sse
BGL_DIR = bgl
BGL_QMP_DIR = bg_bagel
BGQ_DIR = noarch
QCDOC_DIR = qcdoc
NOARCH_DIR = noarch
include ../../../../Makefile.rules
