#LIB_NAME_SET=yes
BGL_DIR = noarch
BGL_QMP_DIR = noarch
BGQ_DIR = noarch
NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS 
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch
include ../../../Makefile.rules
