#LIB_NAME_SET=yes
BGL_DIR = noarch
BGL_QMP_DIR = noarch
BGQ_DIR = noarch
#SEPARATE_LIB=yes
NORECURSE_DIR = CVS noarch qcdsp_nos qcdsp_nos_hdw_diag d_op_impr_dwf
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = noarch
NOARCH_DIR =  noarch
include ../../../Makefile.rules
