#LIB_NAME_SET=yes
#SEPARATE_LIB=yes
NORECURSE_DIR = CVS noarch qcdsp_nos qcdsp_nos_hdw_diag d_op_impr_dwf
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = noarch
QCDSP_DIR = qcdsp_nos
MPI_DIR = 
NOARCH_DIR =  noarch
include ../../../Makefile.rules
