#SEPARATE_LIB=yes
NORECURSE_DIR = CVS  noarch
BGL_DIR = bgl
BGL_QMP_DIR = bg_bagel
QCDOC_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../../Makefile.rules
#include ../../../../Makefile.rules.xlc



