NORECURSE_DIR = qmp qcdoc qcdsp noarch mpi CVS 
BGL_DIR = noarch
BGL_QMP_DIR = noarch
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = noarch
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../../Makefile.rules
