/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _A2A_ARG_H_RPCGEN
#define _A2A_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

CPS_END_NAMESPACE
#include <alg/cg_arg.h>
CPS_START_NAMESPACE

CPS_END_NAMESPACE
#include <alg/qpropw_arg.h>
CPS_START_NAMESPACE

class VML;
class A2AArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int nl;
	int nhits;
	RandomType rand_type;
	int src_width;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_A2AArg (VML *, char *instance, A2AArg*);

#else /* K&R C */
extern  bool_t vml_A2AArg (VML *, char *instance, A2AArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_A2A_ARG_H_RPCGEN */
