#ifndef INCLUDED_ALG_ALL_H
#define INCLUDED_ALG_ALL_H
#include<alg/gparity_contract_arg.h>
#include<alg/alg_smear.h>
#include<alg/alg_pbp.h>
#include<alg/kinetic_smear_arg.h>
#include<alg/w_baryon.h>
#include<alg/diquark.h>
#include<alg/enum.h>
#include<alg/ktopipi_jobparams.h>
#include<alg/ghb_arg.h>
#include<alg/lanc_arg.h>
#include<alg/alg_eig.h>
#include<alg/alg_eq_state.h>
#include<alg/w_hyper_rect.h>
#include<alg/threept_prop_arg.h>
#include<alg/qpropw_arg.h>
#include<alg/muon_arg.h>
#include<alg/prop_dft.h>
#include<alg/meas_arg.h>
#include<alg/wilson_matrix.h>
#include<alg/FourMom.h>
#include<alg/cg_stats.h>
#include<alg/alg_rnd_gauge.h>
#include<alg/hadron_prop_s.h>
#include<alg/alg_fix_gauge.h>
#include<alg/s_spect_arg.h>
#include<alg/quda_arg.h>
#include<alg/no_arg.h>
#include<alg/hmd_arg.h>
#include<alg/lanczos_arg.h>
#include<alg/noise_arg.h>
#include<alg/alg_muon.h>
#include<alg/w_spect_arg.h>
#include<alg/alg_inst.h>
#include<alg/remez_arg.h>
#include<alg/alg_base.h>
#include<alg/qio_prop.h>
#include<alg/meson.h>
#include<alg/eq_state_arg.h>
#include<alg/threept_arg.h>
#include<alg/correlationfunction.h>
#include<alg/w_ferm_vec.h>
#include<alg/pbp_arg.h>
#include<alg/mobius_arg.h>
#include<alg/int_arg.h>
#include<alg/w_axialcurr.h>
#include<alg/eigcg_arg.h>
#include<alg/dens_arg.h>
#include<alg/alg_remez.h>
#include<alg/alg_smear2.h>
#include<alg/dterms.h>
#include<alg/overrelax_arg.h>
//#include<alg/mom_meson_p_s.h>
#include<alg/alg_lanczos.h>
#include<alg/meson_prop_s.h>
#include<alg/alg_nuc3pt.h>
#include<alg/nlocal_prop_s.h>
#include<alg/alg_meas.h>
#include<alg/qpropwGFL.h>
#include<alg/w_ext_mesons.h>
#include<alg/hdcg_arg.h>
#include<alg/nuc3pt_gammar.h>
#include<alg/corrfunc.h>
#include<alg/gamma.h>
#include<alg/qpropw.h>
#include<alg/common_arg.h>
#include<alg/w_momenta.h>
#include<alg/alg_actiondensity.h>
#include<alg/alg_ghb.h>
#include<alg/eig_arg.h>
#include<alg/w_ginfo.h>
#include<alg/w_ext_mesonBE.h>
#include<alg/w_field.h>
#if (defined USE_GRID_A2A ) || (defined USE_BFM_A2A)
#include<alg/a2a/a2a.h>
#endif
#include<alg/cg_arg.h>
#include<alg/propvector.h>
#include<alg/alg_plaq.h>
#include<alg/alg_wline.h>
#include<alg/alg_gparitycontract.h>
#include<alg/alg_s_vacpol.h>
#include<alg/alg_fourier_prop.h>
#include<alg/hyp_smear_arg.h>
#include<alg/w_fuzzing.h>
#include<alg/aots_s.h>
#include<alg/spin_matrix.h>
#include<alg/prop_attribute_arg.h>
#include<alg/hmc_arg.h>
#include<alg/ape_smear_arg.h>
#include<alg/alg_int.h>
#include<alg/fermion_vector.h>
#include<alg/derivative.h>
#include<alg/alg_dens.h>
#include<alg/alg_tcharge.h>
//#include<alg/alg_mom.h>
//#include<alg/mom_arg.h>
#include<alg/fourierprop_arg.h>
#include<alg/nucl_prop_s.h>
#include<alg/myenum.h>
#include<alg/w_mesons.h>
#include<alg/nuc3pt_arg.h>
//#include<alg/nlocal_propmes_s.h>
#include<alg/alg_hmc.h>
#include<alg/pot_arg.h>
#include<alg/alg_pot.h>
//#include<alg/alg_pot2.h>
#include<alg/quark_prop_s.h>
#include<alg/fix_gauge_arg.h>
#include<alg/force_arg.h>
#include<alg/array_arg.h>
#include<alg/propagatorcontainer.h>
#include<alg/nuc2pt.h>
#include<alg/bigfloat.h>
#include<alg/w_gamma_mat.h>
#include<alg/alg_hq_pot.h>
#include<alg/inst_arg.h>
#include<alg/do_arg.h>
#include<alg/alg_noise.h>
#include<alg/nuc3pt.h>
#include<alg/alg_wilsonflow.h>
#include<alg/w_all.h>
#include<alg/propmanager.h>
#include<alg/alg_overrelax.h>
#include<alg/alg_threept.h>
#include<alg/alg_rect.h>
#include<alg/w_quark.h>
#include<alg/bfm_arg.h>
#include<alg/alg_hmd.h>
#include<alg/alg_s_spect.h>
#endif
