/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _GHB_ARG_H_RPCGEN
#define _GHB_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

class VML;
class GhbArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int num_iter;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_GhbArg (VML *, char *instance, GhbArg*);

#else /* K&R C */
extern  bool_t vml_GhbArg (VML *, char *instance, GhbArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_GHB_ARG_H_RPCGEN */
