/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _HMC_ARG_H_RPCGEN
#define _HMC_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

class VML;
class HmcArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int steps_per_traj;
	Float step_size;
	MetropolisType metropolis;
	ReunitarizeType reunitarize;
	ReverseTest reverse;
	ReproduceTest reproduce;
	int reproduce_attempt_limit;
	bool_t wfm_md_sloppy;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_HmcArg (VML *, char *instance, HmcArg*);

#else /* K&R C */
extern  bool_t vml_HmcArg (VML *, char *instance, HmcArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_HMC_ARG_H_RPCGEN */
