/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _INT_ARG_H_RPCGEN
#define _INT_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

class VML;
class IntABArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	IntegratorType type;
	int A_steps;
	int B_steps;
	IntegratorLevel level;
	Float lambda;
};

class VML;
class ActionArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	ForceMeasure force_measure;
	char *force_label;
};

class VML;
class BilinearDescr {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	Float mass;
	int max_num_iter;
};

class VML;
class ActionBilinearArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	   void resize (  u_int nmass ) ;
	FclassType fermion;
	struct {
		u_int bilinears_len;
		BilinearDescr *bilinears_val;
	} bilinears;
	ActionArg action_arg;
};

class VML;
class ApproxDescr {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	RationalApproxType approx_type;
	RationalBoundsType bounds_type;
	Float lambda_low;
	Float lambda_high;
	struct {
		u_int stop_rsd_len;
		Float *stop_rsd_val;
	} stop_rsd;
	   ApproxDescr (  void ) ;
};

class VML;
class RationalDescr {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	FieldType field_type;
	int power_num;
	int power_den;
	long precision;
	Float stop_rsd_fg_mult;
	ApproxDescr md_approx;
	ApproxDescr mc_approx;
	Float stag_bsn_mass;
};

class VML;
class EigenDescr {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	EigenMeasure eigen_measure;
	Float stop_rsd;
	int max_num_iter;
	char *eig_lo_stem;
	char *eig_hi_stem;
};

class VML;
class ActionRationalArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	   void resize (  u_int nmass ) ;
	   void resize (  u_int mass ,  int deg_md ,  int deg_mc ) ;
	ActionBilinearArg bi_arg;
	int remez_generate;
	char *rat_poles_file;
	struct {
		u_int rationals_len;
		RationalDescr *rationals_val;
	} rationals;
	EigenDescr eigen;
};

class VML;
class SplitRange {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int split_low;
	int split_high;
};

class VML;
class ActionRationalSplitArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	   void resize (  u_int nmass ) ;
	struct {
		u_int fractionSplit_len;
		SplitRange *fractionSplit_val;
	} fractionSplit;
};

class VML;
class BosonDescr {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	Float epsilon;
	Float stop_rsd_hb;
};

class VML;
class ActionBosonArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	   void resize (  u_int nmass ) ;
	ActionBilinearArg bi_arg;
	struct {
		u_int bosons_len;
		BosonDescr *bosons_val;
	} bosons;
};

class VML;
class FermionDescr {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	Float epsilon;
	int chrono;
	Float stop_rsd_fg_mult;
	Float stop_rsd_md;
	Float stop_rsd_mc;
};

class VML;
class ActionFermionArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	   void resize (  u_int nmass ) ;
	ActionBilinearArg bi_arg;
	struct {
		u_int fermions_len;
		FermionDescr *fermions_val;
	} fermions;
};

class VML;
class QuotientDescr {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	Float bsn_mass;
	Float bsn_mass_epsilon;
	Float frm_mass;
	Float frm_mass_epsilon;
	int chrono;
	Float stop_rsd_hb;
	Float stop_rsd_fg_mult;
	Float stop_rsd_md;
	Float stop_rsd_mc;
};

class VML;
class ActionQuotientArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	   void resize (  u_int nmass ) ;
	ActionBilinearArg bi_arg;
	struct {
		u_int quotients_len;
		QuotientDescr *quotients_val;
	} quotients;
};

class VML;
class ActionRationalQuotientArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	   void resize (  u_int nmass ) ;
	   void resize (  u_int mass ,  int frm_deg_md ,  int frm_deg_mc ,  int bsn_deg_md ,  int bsn_deg_mc ) ;
	ActionBilinearArg bi_arg;
	Float spread;
	int remez_generate;
	char *rat_poles_file;
	struct {
		u_int bsn_mass_len;
		Float *bsn_mass_val;
	} bsn_mass;
	struct {
		u_int frm_mass_len;
		Float *frm_mass_val;
	} frm_mass;
	struct {
		u_int bosons_len;
		RationalDescr *bosons_val;
	} bosons;
	struct {
		u_int fermions_len;
		RationalDescr *fermions_val;
	} fermions;
	EigenDescr eigen;
};

class VML;
class ActionGaugeArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	GclassType gluon;
	ActionArg action_arg;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_IntABArg (VML *, char *instance, IntABArg*);
extern  bool_t vml_ActionArg (VML *, char *instance, ActionArg*);
extern  bool_t vml_BilinearDescr (VML *, char *instance, BilinearDescr*);
extern  bool_t vml_ActionBilinearArg (VML *, char *instance, ActionBilinearArg*);
extern  bool_t vml_ApproxDescr (VML *, char *instance, ApproxDescr*);
extern  bool_t vml_RationalDescr (VML *, char *instance, RationalDescr*);
extern  bool_t vml_EigenDescr (VML *, char *instance, EigenDescr*);
extern  bool_t vml_ActionRationalArg (VML *, char *instance, ActionRationalArg*);
extern  bool_t vml_SplitRange (VML *, char *instance, SplitRange*);
extern  bool_t vml_ActionRationalSplitArg (VML *, char *instance, ActionRationalSplitArg*);
extern  bool_t vml_BosonDescr (VML *, char *instance, BosonDescr*);
extern  bool_t vml_ActionBosonArg (VML *, char *instance, ActionBosonArg*);
extern  bool_t vml_FermionDescr (VML *, char *instance, FermionDescr*);
extern  bool_t vml_ActionFermionArg (VML *, char *instance, ActionFermionArg*);
extern  bool_t vml_QuotientDescr (VML *, char *instance, QuotientDescr*);
extern  bool_t vml_ActionQuotientArg (VML *, char *instance, ActionQuotientArg*);
extern  bool_t vml_ActionRationalQuotientArg (VML *, char *instance, ActionRationalQuotientArg*);
extern  bool_t vml_ActionGaugeArg (VML *, char *instance, ActionGaugeArg*);

#else /* K&R C */
extern  bool_t vml_IntABArg (VML *, char *instance, IntABArg*);
extern  bool_t vml_ActionArg (VML *, char *instance, ActionArg*);
extern  bool_t vml_BilinearDescr (VML *, char *instance, BilinearDescr*);
extern  bool_t vml_ActionBilinearArg (VML *, char *instance, ActionBilinearArg*);
extern  bool_t vml_ApproxDescr (VML *, char *instance, ApproxDescr*);
extern  bool_t vml_RationalDescr (VML *, char *instance, RationalDescr*);
extern  bool_t vml_EigenDescr (VML *, char *instance, EigenDescr*);
extern  bool_t vml_ActionRationalArg (VML *, char *instance, ActionRationalArg*);
extern  bool_t vml_SplitRange (VML *, char *instance, SplitRange*);
extern  bool_t vml_ActionRationalSplitArg (VML *, char *instance, ActionRationalSplitArg*);
extern  bool_t vml_BosonDescr (VML *, char *instance, BosonDescr*);
extern  bool_t vml_ActionBosonArg (VML *, char *instance, ActionBosonArg*);
extern  bool_t vml_FermionDescr (VML *, char *instance, FermionDescr*);
extern  bool_t vml_ActionFermionArg (VML *, char *instance, ActionFermionArg*);
extern  bool_t vml_QuotientDescr (VML *, char *instance, QuotientDescr*);
extern  bool_t vml_ActionQuotientArg (VML *, char *instance, ActionQuotientArg*);
extern  bool_t vml_ActionRationalQuotientArg (VML *, char *instance, ActionRationalQuotientArg*);
extern  bool_t vml_ActionGaugeArg (VML *, char *instance, ActionGaugeArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_INT_ARG_H_RPCGEN */
