/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _MATRIXPOLYNOMIAL_ARG_H_RPCGEN
#define _MATRIXPOLYNOMIAL_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

class VML;
class MatrixPolynomialArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int Npol;
	struct {
		u_int params_len;
		Float *params_val;
	} params;
	Float *tmp1;
	Float *tmp2;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_MatrixPolynomialArg (VML *, char *instance, MatrixPolynomialArg*);

#else /* K&R C */
extern  bool_t vml_MatrixPolynomialArg (VML *, char *instance, MatrixPolynomialArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_MATRIXPOLYNOMIAL_ARG_H_RPCGEN */
