/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _MOBIUS_ARG_H_RPCGEN
#define _MOBIUS_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

class VML;
class MobiusArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	Float mobius_b_coeff;
	Float mobius_c_coeff;
	struct {
		u_int zmobius_b_coeff_len;
		Float *zmobius_b_coeff_val;
	} zmobius_b_coeff;
	struct {
		u_int zmobius_c_coeff_len;
		Float *zmobius_c_coeff_val;
	} zmobius_c_coeff;
	int ls;
	Float M5;
	CgArg cg;
	struct {
		u_int rsd_vec_len;
		Float *rsd_vec_val;
	} rsd_vec;
	int use_single_precision;
	   MobiusArg (  ) ;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_MobiusArg (VML *, char *instance, MobiusArg*);

#else /* K&R C */
extern  bool_t vml_MobiusArg (VML *, char *instance, MobiusArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_MOBIUS_ARG_H_RPCGEN */
