/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _MOM_ARG_H_RPCGEN
#define _MOM_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

class VML;
class MomArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int no_of_momenta;
	int deg;
	int dir;
	int src_begin[4];
	int src_end[4];
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_MomArg (VML *, char *instance, MomArg*);

#else /* K&R C */
extern  bool_t vml_MomArg (VML *, char *instance, MomArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_MOM_ARG_H_RPCGEN */
