/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _NOISE_ARG_H_RPCGEN
#define _NOISE_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

enum NoiseType {
	GAUSSIAN = 0,
	FLAT = 1,
};
typedef enum NoiseType NoiseType;
extern struct vml_enum_map NoiseType_map[];

class VML;
class NoiseArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	NoiseType noise_kind;
	Float size;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_NoiseType (VML *, char *instance, NoiseType*);
extern  bool_t vml_NoiseArg (VML *, char *instance, NoiseArg*);

#else /* K&R C */
extern  bool_t vml_NoiseType (VML *, char *instance, NoiseType*);
extern  bool_t vml_NoiseArg (VML *, char *instance, NoiseArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_NOISE_ARG_H_RPCGEN */
