/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _S_SPECT_ARG_H_RPCGEN
#define _S_SPECT_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

enum StagQuarkSrcType {
	S_QUARK_POINT = 0,
	WALLZ = 1,
	WALL2Z = 2,
};
typedef enum StagQuarkSrcType StagQuarkSrcType;
extern struct vml_enum_map StagQuarkSrcType_map[];

enum StagQuarkLocalType {
	LOCAL = 0,
	NONLOCAL = 1,
};
typedef enum StagQuarkLocalType StagQuarkLocalType;
extern struct vml_enum_map StagQuarkLocalType_map[];

enum StagQuarkDir {
	HDM_X = 0,
	HDM_Y = 1,
	HDM_Z = 2,
	HDM_T = 3,
};
typedef enum StagQuarkDir StagQuarkDir;
extern struct vml_enum_map StagQuarkDir_map[];

class VML;
class StagQuarkSrc {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	StagQuarkSrcType type;
	int origin[4];
	int end[4];
	StagQuarkDir dir;
};

class VML;
class StagQuarkArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int qid;
	CgArg cg;
	StagQuarkSrc src;
	StagQuarkLocalType sln;
};

class VML;
class StagMesonArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int qid0;
	int qid1;
	StagQuarkDir dir;
	u_long meson_buf;
};

class VML;
class StagMomMesonArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int qid0;
	int qid1;
	StagQuarkDir dir;
	int no_of_momenta;
	u_long meson_buf;
};

class VML;
class StagNucleonArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int qid0;
	int qid1;
	int qid2;
	StagQuarkDir dir;
	u_long nucleon_buf;
};

class VML;
class StagNonLocalArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int qid0;
	int qid1;
	int qid2;
	StagQuarkDir dir;
	u_long nlocal_buf;
};

class VML;
class NLStagMesonArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int qid0[8];
	StagQuarkDir dir;
	u_long nlocal_buf;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_StagQuarkSrcType (VML *, char *instance, StagQuarkSrcType*);
extern  bool_t vml_StagQuarkLocalType (VML *, char *instance, StagQuarkLocalType*);
extern  bool_t vml_StagQuarkDir (VML *, char *instance, StagQuarkDir*);
extern  bool_t vml_StagQuarkSrc (VML *, char *instance, StagQuarkSrc*);
extern  bool_t vml_StagQuarkArg (VML *, char *instance, StagQuarkArg*);
extern  bool_t vml_StagMesonArg (VML *, char *instance, StagMesonArg*);
extern  bool_t vml_StagMomMesonArg (VML *, char *instance, StagMomMesonArg*);
extern  bool_t vml_StagNucleonArg (VML *, char *instance, StagNucleonArg*);
extern  bool_t vml_StagNonLocalArg (VML *, char *instance, StagNonLocalArg*);
extern  bool_t vml_NLStagMesonArg (VML *, char *instance, NLStagMesonArg*);

#else /* K&R C */
extern  bool_t vml_StagQuarkSrcType (VML *, char *instance, StagQuarkSrcType*);
extern  bool_t vml_StagQuarkLocalType (VML *, char *instance, StagQuarkLocalType*);
extern  bool_t vml_StagQuarkDir (VML *, char *instance, StagQuarkDir*);
extern  bool_t vml_StagQuarkSrc (VML *, char *instance, StagQuarkSrc*);
extern  bool_t vml_StagQuarkArg (VML *, char *instance, StagQuarkArg*);
extern  bool_t vml_StagMesonArg (VML *, char *instance, StagMesonArg*);
extern  bool_t vml_StagMomMesonArg (VML *, char *instance, StagMomMesonArg*);
extern  bool_t vml_StagNucleonArg (VML *, char *instance, StagNucleonArg*);
extern  bool_t vml_StagNonLocalArg (VML *, char *instance, StagNonLocalArg*);
extern  bool_t vml_NLStagMesonArg (VML *, char *instance, NLStagMesonArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_S_SPECT_ARG_H_RPCGEN */
