/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _W_SPECT_ARG_H_RPCGEN
#define _W_SPECT_ARG_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE

enum MesonLimits {
	NumMesonChannels = 16,
};
typedef enum MesonLimits MesonLimits;
extern struct vml_enum_map MesonLimits_map[];

class VML;
class WspectOutput {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	WbaryonFold fold;
	char *cg;
	char *cg2;
	char *pbp;
	char *mid_point;
	char *a0_p;
	char *a1;
	char *b1;
	char *pion;
	char *pion_prime;
	char *rho;
	char *rho_prime;
	char *meson_name00;
	char *meson_name01;
	char *meson_name02;
	char *meson_name03;
	char *meson_name04;
	char *meson_name05;
	char *meson_name06;
	char *meson_name07;
	char *meson_name08;
	char *meson_name09;
	char *meson_name10;
	char *meson_name11;
	char *meson_name12;
	char *meson_name13;
	char *meson_name14;
	char *meson_name15;
	char *nucleon;
	char *nucleon_prime;
	char *delta_x;
	char *delta_y;
	char *delta_z;
	char *delta_t;
	   WspectOutput (  ) ;
};

class VML;
class WspectArg {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	char *CgArgFile;
	char *WspectOutputFile;
	int prop_dir;
	int num_mom;
	int midplane;
	SourceKind source_kind;
	int src_box_b[4];
	int src_box_e[4];
	SinkKind sink_kind;
	int snk_box_b[4];
	int snk_box_e[4];
	int zero_mom_box_snk;
	Float g_epsi;
	int g_n;
	int g_center[4];
	Float rescale_factor;
	int aots_num;
	int aots_start;
	int aots_step;
	int baryons_on;
	int normal_mesons_on;
	int extended_mesons_on;
	int extended_mesonsBE_on;
	int extended_mesons_op_groupId;
	int extended_mesons_first_dev_on;
	int extended_mesons_second_sym_dev_on;
	int extended_mesons_second_antisym_dev_on;
	int extended_mesons_second_diag_dev_on;
	int fuzzing_on;
	int sink_fuzzing_only;
	int fuzzing_level;
	int fuzzing_c_num;
	Float fuzzing_c[MAX_FUZZING_C_NUM];
	int fuzzing_hits;
	int extended_mesonsBE_op_groupId;
	int extended_mesonsBE_Elec_on;
	int extended_mesonsBE_Magn_on;
	int BEfuzzing_on;
	int BEfuzzing_level;
	int BEfuzzing_c_num;
	Float BEfuzzing_c[MAX_FUZZING_C_NUM];
	int BEfuzzing_hits;
	   WspectArg (  ) ;
};

/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_MesonLimits (VML *, char *instance, MesonLimits*);
extern  bool_t vml_WspectOutput (VML *, char *instance, WspectOutput*);
extern  bool_t vml_WspectArg (VML *, char *instance, WspectArg*);

#else /* K&R C */
extern  bool_t vml_MesonLimits (VML *, char *instance, MesonLimits*);
extern  bool_t vml_WspectOutput (VML *, char *instance, WspectOutput*);
extern  bool_t vml_WspectArg (VML *, char *instance, WspectArg*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_W_SPECT_ARG_H_RPCGEN */
