NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS 
BGL_QMP_DIR = noarch
QCDOC_DIR = noarch
QCDOC_SERIAL_DIR = noarch
QCDSP_DIR = qcdsp
MPI_DIR = noarch
NOARCH_DIR = noarch
include ../../../../../Makefile.rules
