SEPARATE_LIB=no
BGL_DIR = noarch
BGL_QMP_DIR = noarch
NORECURSE_DIR = qcdoc_cpp qcdoc qcdsp noarch mpi CVS 
QCDOC_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = noarch
NOARCH_DIR = noarch
include ../../../../Makefile.rules
