NORECURSE_DIR = qmp qcdoc qcdsp noarch mpi CVS 
BGL_DIR = noarch
BGL_QMP_DIR = qmp
BGQ_DIR = noarch
QCDOC_DIR =  qcdoc
QCDOC_SERIAL_DIR =  qcdoc
NOARCH_DIR =  noarch
include ../../../../Makefile.rules
  
