NORECURSE_DIR = bgl qcdoc qcdsp noarch mpi qmp CVS quda 
BGL_DIR = bgl
BGL_QMP_DIR = bgl
BGQ_DIR = bgl
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch
PWD = $(shell pwd)
include ../../../../Makefile.rules
