NORECURSE_DIR = bgl qcdoc qcdsp noarch mpi qmp CVS 
BGL_DIR = bgl
BGL_QMP_DIR = bgl
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = noarch
MPI_DIR = mpi
NOARCH_DIR = noarch
PWD = $(shell pwd)
include ../../../../Makefile.rules
