NORECURSE_DIR = qcdoc qcdsp noarch mpi qmp CVS 
BGL_QMP_DIR = qmp
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = noarch
MPI_DIR = mpi
NOARCH_DIR = noarch
PWD = $(shell pwd)
include ../../../../Makefile.rules
