#SEPARATE_LIB=yes
BGL_DIR = noarch
BGL_QMP_DIR = noarch
BGQ_DIR = noarch
NORECURSE_DIR = glb_cpp glb_passthru CVS 
QCDOC_DIR = glb_cpp
NOARCH_DIR = 
NOARCH_BFM_DIR = 
NOARCH_BFM_QMP_DIR = 
include ../../../Makefile.rules
