#SEPARATE_LIB=yes
NORECURSE_DIR = CVS  bgl noarch qcdoc qcdsp qcdsp_lcl_nos qcdsp_nos qcdsp_nos_hdw_diag qcdsp_scl noarch_pv bgp bgp_asm bg_bagel bg_bagel_spi bgl
BGL_DIR = bgl
BGQ_DIR = bg_bagel
BGL_QMP_DIR = bg_bagel
QCDOC_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../../Makefile.rules
