NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS 
BGL_DIR = noarch
BGL_QMP_DIR = noarch
BGQ_DIR = noarch
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../../../Makefile.rules
