#SEPARATE_LIB=yes
NORECURSE_DIR = CVS bgl qcdoc noarch qcdsp_nos qcdsp_nos_hdw_diag qmp sse bfm quda
BGL_DIR = bgl
BGL_QMP_DIR = bgl
BGQ_DIR = bfm noarch
NOARCH_DIR =  noarch
#include ../../../../Makefile.rules.xlc
#include ../../../../Makefile.rules.sse
include ../../../../Makefile.rules
