SEPARATE_LIB=yes
NORECURSE_DIR = CVS bgl qcdoc noarch qcdsp_nos qcdsp_nos_hdw_diag qmp
BGL_DIR = bgl
BGL_QMP_DIR = bgl noarch
QCDOC_DIR = qcdoc
QCDSP_DIR = qcdsp_nos
MPI_DIR = mpi
NOARCH_DIR =  noarch
include ../../../../Makefile.rules
