#SEPARATE_LIB=yes
NORECURSE_DIR = CVS bgl qcdoc noarch qcdsp_nos qcdsp_nos_hdw_diag qmp sse bfm quda
BGL_DIR = bgl
BGL_QMP_DIR = bgl
BGQ_DIR = bfm noarch
QCDOC_DIR = qcdoc
NOARCH_DIR =  quda
include ../../../../Makefile.rules
# DO NOT DELETE
