#SEPARATE_LIB = yes
NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS bgq
BGL_DIR = qcdoc
BGL_QMP_DIR = qcdoc
BGQ_DIR = qcdoc
NOARCH_DIR = qcdoc
NOARCH_BFM_DIR = noarch  #for qcdoc version, only qmp ParTransGauge works with G-parity atm.
NOARCH_BFM_QMP_DIR = qcdoc
include ../../../../Makefile.rules
