#SEPARATE_LIB=yes
NORECURSE_DIR = CVS bgl noarch qmp sse
BGL_DIR = noarch
BGL_QMP_DIR = noarch
BGQ_DIR = noarch
NOARCH_DIR =  noarch
#NOARCH_DIR =  sse

#include ../../../../Makefile.rules.xlc
#include ../../../../Makefile.rules.sse
include ../../../../Makefile.rules


