NORECURSE_DIR = qcdoc qcdsp noarch mpi qmp bgl_qmp CVS 
BGL_DIR = noarch
BGL_QMP_DIR = bgl_qmp
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../../Makefile.rules
