NORECURSE_DIR = qcdoc qcdsp noarch mpi qmp bgl_qmp CVS 
BGL_DIR = noarch
BGL_QMP_DIR = bgl_qmp
BGQ_DIR = noarch
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch
include ../../../../Makefile.rules
