#SEPARATE_LIB = yes
NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS 
BGL_DIR = noarch
BGL_QMP_DIR = noarch
BGQ_DIR = noarch
NOARCH_DIR = qcdoc
NOARCH_BFM_DIR = noarch
NOARCH_BFM_QMP_DIR = noarch
include ../../../../Makefile.rules
