#all: cpsMPI.x sse-wilson_dslash.s
all: cpsMPI.x

pull:
	git pull origin

push:
	git push origin


test: cpsMPI.x
	sh ./test.sh


OBJDIR=/home/meifeng/code/GIT/CPS508/objs-debug
ROOT=$(OBJDIR)

clean:
	/bin/rm -f *.o *.x


CC=$(ROOT)/mpicc
CXX=$(ROOT)/mpic++



DFLAGS =  -DUSE_QMP -DUSE_QIO

INCLUDES =  -I $(OBJDIR)/ -I $(OBJDIR)/../include/ \
  -I/home/izubuchi/lib/qmp-2.3.1/include    \
  -I/home/izubuchi/lib/qio-2.3.8/include \
  $(DFLAGS)

#Taku original
#ICCOPT= -openmp -cxxlib-gcc -g -O1 -mp -fno-alias  -i-static $(INCLUDES)

#Kishikawa
#ICCOPT= -openmp -g -O2 -xT -cxxlib-gcc -align -inline-max-total-size=10000 -ip  -i-static $(INCLUDES)

# this is 55.85 % 
ICCOPT=  -openmp -g -O2 -xS  -fno-alias  -align -inline-max-total-size=10000 -ip  -i-static $(INCLUDES)

# more agressive options
#ICCOPT=  -openmp -g -fomit-frame-pointer -restrict -O2  -xT  -fno-alias  -align -inline-max-total-size=10000 -ip  -i-static $(INCLUDES)

#this is 43 %
#ICCOPT=  -openmp -g -O1 -xT  -fno-alias  -align -inline-max-total-size=10000 -ip  -i-static $(INCLUDES)

# perhaps better to use O3
#ICCOPT=  -openmp -g -O3 -xT  -fno-alias  -align -inline-max-total-size=10000 -ip  -i-static $(INCLUDES)

#ICCOPT= -openmp -g -O2 -xT -cxxlib-gcc -align -fno-alias -inline-max-total-size=10000 -ipo  -i-static $(INCLUDES)


#ICCOPT=  -openmp -g -O0 -xT  -fno-alias  -align -inline-max-total-size=10000 -ip  -i-static $(INCLUDES)

# GCC option, perhaps good for opteron
#GCCOPT=-O1 -msse3 -march=opteron -mtune=opteron -fomit-frame-pointer -fno-unroll-loops -fstrict-aliasing -static -fopenmp $(INCLUDES)

GCCOPT= -fopenmp -g -O3


INTEL_LIBS=
#INTEL_LIBS= $(MKLROOT)/../lib/intel64/libguide.a $(MKLROOT)/../lib/intel64/libirc.a
#INTEL_LIBS= $(MKLROOT)/../lib/ia32/libguide.a $(MKLROOT)/../lib/ia32/libirc.a

HEADERS =    sse-blk-dag1.h  sse-macros-dag0.h sse-macros-dag1.h \
sse-bnd-dag0.h sse-bnd-dag1.h  sse-blk-dag0.h  sse-inlines.h  sse-subs.h test-order.h 


main.o: main.C
	$(CXX) $(ICCOPT)  -c  $<

#dirc objects
DOBJDIR= $(ROOT)/../main/sse_f_dwf_inv/
OBJS=  $(DOBJDIR)/sse-wilson_dslash.o  $(DOBJDIR)/wilson_init.o $(DOBJDIR)/wilson_end.o \
        $(DOBJDIR)/sse-dwf_dslash_4.o $(DOBJDIR)/dwf_dslash.o  $(DOBJDIR)/dwf_dslash_5_plus.o 

cpsMPI.x: main.o
	$(CXX) $(ICCOPT) main.o  \
        $(OBJDIR)/cps-e.a  $(INTEL_LIBS)  \
	$(OBJS) \
        /home/izubuchi/lib/qmp-2.3.1/lib/libqmp.a \
        /home/izubuchi/lib/qio-2.3.8/lib/libqio.a \
        /home/izubuchi/lib/qio-2.3.8/lib/liblime.a \
        /home/izubuchi/Work/CPS508/aux/GotoBLAS2/libgoto2.a \
        -o cpsMPI.x
