#LIB_NAME_SET=yes
BGL_QMP_DIR = noarch
NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS 
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../Makefile.rules
