#SEPARATE_LIB=yes
BGL_QMP_DIR = noarch
NORECURSE_DIR = CVS  noarch qcdoc qcdsp qcdsp_lcl_nos qcdsp_nos qcdsp_nos_hdw_diag qcdsp_scl
QCDOC_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../../Makefile.rules
