#LIB_NAME_SET=yes
NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS 
BGL_DIR = noarch
BGQ_DIR = noarch
BGL_QMP_DIR = noarch
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch
include ../../../Makefile.rules
