/* lib/wfm_options_internal.h.  Generated by configure.  */
/* lib/wfm_options_internal.h.in.  Generated from configure.ac by autoheader.  */

/* Default to BG/L kernels */
#define BLUE_GENE_IS_DEFAULT 1

/* Name of package */
#define PACKAGE "bagel_wilson_dslash"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "paboyle@ph.ed.ac.uk"

/* Define to the full name of this package. */
#define PACKAGE_NAME "bagel_wilson_dslash"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "bagel_wilson_dslash 1.4.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "bagel_wilson_dslash"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.4.3"

/* Use Fake Comms */
/* #undef USE_COMMS_FAKE */

/* Use GM Comms */
/* #undef USE_COMMS_GM */

/* Use MPI Comms */
/* #undef USE_COMMS_MPI */

/* Use No Comms */
/* #undef USE_COMMS_NONE */

/* Use QMP Comms */
/*#define USE_COMMS_QMP 1 */

/* Use SCU Comms */
/* #undef USE_COMMS_SCU */

#define USE_COMMS_SPI 1 

/* Use Double Precision */
#define USE_DOUBLE 1

/* Use Gmalloc Alocator */
/* #undef USE_GMALLOC */

/* Use Malloc Allocator */
/* #undef USE_MALLOC */

/* Use memalign to allocate */
#define USE_MEMALIGN 

/* Use POSIX Memalign to allocate */
/* #undef USE_POSIX_MEMALIGN */

/* Use Qalloc Allocator */
/* #undef USE_QALLOC */

/* Use QMP allocator */
/* #define USE_QMPALLOC 1 */

/* Enable BGL MMU optimisations - requires hacked kernel */
#define USE_SWOA  1

/* Use BlueGene/L co-routines */
/* #undef USE_THREADS_BGL */

/* Use fake threading */
/* #undef USE_THREADS_FAKE */

/* Use NO threading */
#define USE_THREADS_NONE 1

/* Use POSIX threads */
/* #undef USE_THREADS_POSIX */

/* Version number of package */
#define VERSION "1.4.3"

/* Allocator Alignment */
#define WFM_ALIGN_ARG 128
