NORECURSE_DIR = mpi qcdsp noarch qcdoc CVS 
BGL_DIR = noarch
BGL_QMP_DIR = noarch
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
PWD = $(shell pwd)
include ../../../Makefile.rules
