#! /bin/sh

# Remove all the file generated by doxygen.

if [ ! -e usr/header.html ]
then
	mv usr/html/header.html usr
fi
rm -f usr/html/*  ref/html/* usr/doxtag ref/doxtag ref/doxywarnings
cp usr/header.html usr/html 

