# $Id: cleandocs.sh,v 1.4 2004-09-02 16:51:48 zs Exp $
# Remove all the files generated by doxygen.
# This script is really meant to be called from Makefile_cps and so the
# CPS directory structure is assumed. However it can still be useful to use
# this as a stand-alone script. The bottom line is that this script expects 
# to be called from its own directory or its parent directory.


docdir=$PWD
if [ `basename $docdir` != 'doc' ]
then
docdir=$PWD/doc
fi


if [ ! -e $docdir/usr/header.html ]
then
	mv $docdir/usr/html/header.html $docdir/usr
fi
rm -f $docdir/usr/html/*  $docdir/ref/html/* $docdir/usr/doxtag $docdir/ref/doxtag $docdir/ref/doxywarnings
mv $docdir/usr/header.html $docdir/usr/html 

for d in changelog manual mpi-scu new_structure porting qcdio qcdsp roadmap structure testing
do
    make -C $docdir/$d realclean
done

rm -rf $docdir/examples/s_spect $docdir/examples/t_asqtad_pion $docdir/examples/t_gauge_rot

