NORECURSE_DIR = qcdoc qcdsp noarch mpi qmp CVS 
BGL_DIR = noarch
BGL_QMP_DIR = qmp
BGQ_DIR = qmp
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch
PWD = $(shell pwd)
include ../../../Makefile.rules
