NORECURSE_DIR = qmp qcdoc qcdsp noarch mpi bg_asm CVS 
BGL_DIR = noarch
BGL_QMP_DIR = qmp bg_asm
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../../Makefile.rules
