#SEPARATE_LIB = yes
NORECURSE_DIR = qmp qcdoc qcdsp noarch mpi bg_asm CVS  bagel_c qmp-sse qcdoc_asm
BGL_DIR = noarch
BGL_QMP_DIR = qmp bg_asm
BGQ_DIR = qmp
NOARCH_DIR = noarch qmp 
include ../../../../Makefile.rules

