#SEPARATE_LIB = yes
NORECURSE_DIR = qmp qcdoc qcdsp noarch mpi bg_asm CVS qcdoc_asm
BGL_DIR = noarch
BGL_QMP_DIR = qmp bg_asm
BGQ_DIR = qmp qcdoc_asm
NOARCH_DIR = qmp noarch
#if QMP is enabled, the optimised QMP version will be used
NOARCH_DIR = noarch qmp
NOARCH_BFM_DIR = noarch qmp bagel_c
NOARCH_BFM_QMP_DIR = noarch qmp bagel_c qcdoc_asm bg_asm
include ../../../../Makefile.rules

