#SEPARATE_LIB=yes
NORECURSE_DIR = CVS bgl noarch qmp sse
BGL_DIR = noarch
BGL_QMP_DIR = noarch
BGQ_DIR = noarch
NOARCH_DIR =  noarch
#NOARCH_DIR =  sse
NOARCH_BFM_DIR =  noarch
NOARCH_BFM_QMP_DIR =  noarch

#include ../../../../Makefile.rules.xlc
#include ../../../../Makefile.rules.sse
include ../../../../Makefile.rules


