NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS 
BGL_DIR = noarch
BGL_QMP_DIR = noarch
QCDOC_DIR = noarch
QCDOC_SERIAL_DIR = noarch
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
PWD = $(shell pwd)
include ../../../Makefile.rules
