#SEPARATE_LIB=yes
NORECURSE_DIR = bgl qcdoc qcdsp noarch mpi CVS 
BGL_DIR = bgl
BGL_QMP_DIR = bgl
BGQ_DIR = noarch
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch
include ../../../Makefile.rules
