NORECURSE_DIR = bgl qcdoc qcdsp noarch mpi CVS 
BGL_DIR = bgl
BGL_QMP_DIR = qcdoc
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
QCDSP_DIR = qcdsp
MPI_DIR = mpi
NOARCH_DIR = noarch
include ../../../Makefile.rules
